In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [3]:
url = "https://en.wikipedia.org/wiki/List_of_Indians_by_net_worth"
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.7559.134'}
 
page = requests.get(url, headers=headers)
soup = BeautifulSoup(page.content, 'html.parser')
soup

<!DOCTYPE html>

<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available" dir="ltr" lang="en">
<head>
<meta charset="utf-8"/>
<title>List of Indians by net worth - Wikipedia</title>
<script>(function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available";var cookie=document.cookie.match(/(?:^|; )enwikimwclientpreferences=([^;]+)/);if(cookie){cookie[1].split('%2C').forEach(function(pref){className=className.replace(new RegExp('(^| )'+pref.replace(/-clientpref-\w+$|[^\w-]+/g,'')+'-clientpref-\\w+( |$)'),'$1'+pref+'$2');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"7766ae79-29e9-4a6f-89d6-a9cd53f3a6a9","wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"List_of_Indians_by_net_worth","wgTitle":"List of Indians by net worth","wgCurRevisionId":1287250003,"wgRevisionId":1287250003,"wgArticleId":61238433,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["Articles with short description","Short description is different from Wikidata","Wikipedia indefinitely semi-protected pages","Indian billionaires","Demographics of India","Lists of Indian people","Lists of people by wealth","Economy of India lists"],"wgPageViewLanguage":"en","wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"List_of_Indians_by_net_worth","wgRelevantArticleId":61238433,"wgTempUserName":null,"wgIsProbablyEditable":false,"wgRelevantPageIsProbablyEditable":false,"wgRestrictionEdit":["autoconfirmed"],"wgRestrictionMove":["autoconfirmed"],"wgNoticeProject":"wikipedia","wgFlaggedRevsParams":{"tags":{"status":{"levels":1}}},"wgConfirmEditCaptchaNeededForGenericEdit":"hcaptcha","wgConfirmEditHCaptchaVisualEditorOnLoadIntegrationEnabled":false,"wgConfirmEditHCaptchaSiteKey":"5d0c670e-a5f4-4258-ad16-1f42792c9c62","wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgPopupsFlags":0,"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":false,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":6000,"wgEditSubmitButtonLabelPublish":true,"wgVisualEditorPageIsDisambiguation":false,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":false,"wgVector2022LanguageInHeader":true,"wgULSisLanguageSelectorEmpty":false,"wgWikibaseItemId":"Q1861515","wgCheckUserClientHintsHeadersJsApi":["brands","architecture","bitness","fullVersionList","mobile","model","platform","platformVersion"],"GEHomepageSuggestedEditsEnableTopics":true,"wgGESuggestedEditsTaskTypes":{"taskTypes":["copyedit","link-recommendation"],"unavailableTaskTypes":[]},"wgGETopicsMatchModeEnabled":false,"wgGELevelingUpEnabledForUser":false,"wgGEUseTestKitchenExtension":true,"wgMetricsPlatformUserExperiments":{"active_experiments":[],"overrides":[],"enrolled":[],"assigned":[],"subject_ids":[],"sampling_units":[],"coordinator":[]},"wgTestKitchenUserExperiments":{"active_experiments":[],"overrides":[],"enrolled":[],"assigned":[],"subject_ids":[],"sampling_units":[],"coordinator":[]}};
RLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.wikimediamessages.styles":"ready","ext.cite.styles":"ready","skins.vector.search.codex.styles":"ready","skins.vector.styles":"ready","skins.vector.icons":"ready","jquery.tablesorter.styles":"ready","jquery.makeCollapsible.styles":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","wikibase.client.init":"ready"};RLPAGEMODULES=["ext.cite.ux-enhancements","site","mediawiki.page.ready","jquery.tablesorter","jquery.makeCollapsible","mediawiki.toc","skins.vector.js","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.gadget.ReferenceTooltips","ext.gadget.switcher","ext.urlShortener.toolbar","ext.centralauth.centralautologin","mmv.bootstrap","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.echo.centralauth","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.interface","ext.cx.eventlogging.campaigns","ext.cx.uls.quick.actions","wikibase.client.vector-2022","wikibase.databox.fromWikidata","ext.checkUser.clientHints","ext.growthExperiments.SuggestedEditSession","ext.xLab","ext.testKitchen"];</script>
<script>(RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return["user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});
}];});});</script>
<link href="/w/load.php?lang=en&amp;modules=ext.cite.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediamessages.styles%7Cjquery.makeCollapsible.styles%7Cjquery.tablesorter.styles%7Cskins.vector.icons%2Cstyles%7Cskins.vector.search.codex.styles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<script async="" src="/w/load.php?lang=en&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector-2022"></script>
<meta content="" name="ResourceLoaderDynamicStyles"/>
<link href="/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<meta content="MediaWiki 1.46.0-wmf.14" name="generator"/>
<meta content="origin" name="referrer"/>
<meta content="origin-when-cross-origin" name="referrer"/>
<meta content="max-image-preview:standard" name="robots"/>
<meta content="telephone=no" name="format-detection"/>
<meta content="width=1120" name="viewport"/>
<meta content="List of Indians by net worth - Wikipedia" property="og:title"/>
<meta content="website" property="og:type"/>
<link href="//upload.wikimedia.org" rel="preconnect"/>
<link href="/static/apple-touch/wikipedia.png" rel="apple-touch-icon"/>
<link href="/static/favicon/wikipedia.ico" rel="icon"/>
<link href="/w/rest.php/v1/search" rel="search" title="Wikipedia (en)" type="application/opensearchdescription+xml"/>
<link href="//en.wikipedia.org/w/api.php?action=rsd" rel="EditURI" type="application/rsd+xml"/>
<link href="https://en.wikipedia.org/wiki/List_of_Indians_by_net_worth" rel="canonical"/>
<link href="https://creativecommons.org/licenses/by-sa/4.0/deed.en" rel="license"/>
<link href="/w/index.php?title=Special:RecentChanges&amp;feed=atom" rel="alternate" title="Wikipedia Atom feed" type="application/atom+xml"/>
<link href="//meta.wikimedia.org" rel="dns-prefetch">
<link href="auth.wikimedia.org" rel="dns-prefetch"/>
</link></head>
<body class="skin--responsive skin-vector skin-vector-search-vue mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject page-List_of_Indians_by_net_worth rootpage-List_of_Indians_by_net_worth skin-vector-2022 action-view">
<div aria-live="polite" class="mw-aria-live-region" id="mw-aria-live-region"></div><a class="mw-jump-link" href="#bodyContent">Jump to content</a>
<div class="vector-header-container">
<header class="vector-header mw-header no-font-mode-scale">
<div class="vector-header-start">
<nav aria-label="Site" class="vector-main-menu-landmark">
<div class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right" id="vector-main-menu-dropdown" title="Main menu">
<input aria-haspopup="true" aria-label="Main menu" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-main-menu-dropdown" id="vector-main-menu-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-main-menu-dropdown-checkbox" id="vector-main-menu-dropdown-label"><span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu"></span>
<span class="vector-dropdown-label-text">Main menu</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-unpinned-container" id="vector-main-menu-unpinned-container">
<div class="vector-main-menu vector-pinnable-element" id="vector-main-menu">
<div class="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned" data-feature-name="main-menu-pinned" data-pinnable-element-id="vector-main-menu" data-pinned-container-id="vector-main-menu-pinned-container" data-unpinned-container-id="vector-main-menu-unpinned-container">
<div class="vector-pinnable-header-label">Main menu</div>
<button class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">move to sidebar</button>
<button class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">hide</button>
</div>
<div class="vector-menu mw-portlet mw-portlet-navigation" id="p-navigation">
<div class="vector-menu-heading">
		Navigation
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="n-mainpage-description"><a accesskey="z" href="/wiki/Main_Page" title="Visit the main page [z]"><span>Main page</span></a></li><li class="mw-list-item" id="n-contents"><a href="/wiki/Wikipedia:Contents" title="Guides to browsing Wikipedia"><span>Contents</span></a></li><li class="mw-list-item" id="n-currentevents"><a href="/wiki/Portal:Current_events" title="Articles related to current events"><span>Current events</span></a></li><li class="mw-list-item" id="n-randompage"><a accesskey="x" href="/wiki/Special:Random" title="Visit a randomly selected article [x]"><span>Random article</span></a></li><li class="mw-list-item" id="n-aboutsite"><a href="/wiki/Wikipedia:About" title="Learn about Wikipedia and how it works"><span>About Wikipedia</span></a></li><li class="mw-list-item" id="n-contactpage"><a href="//en.wikipedia.org/wiki/Wikipedia:Contact_us" title="How to contact Wikipedia"><span>Contact us</span></a></li>
</ul>
</div>
</div>
<div class="vector-menu mw-portlet mw-portlet-interaction" id="p-interaction">
<div class="vector-menu-heading">
		Contribute
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="n-help"><a href="/wiki/Help:Contents" title="Guidance on how to use and edit Wikipedia"><span>Help</span></a></li><li class="mw-list-item" id="n-introduction"><a href="/wiki/Help:Introduction" title="Learn how to edit Wikipedia"><span>Learn to edit</span></a></li><li class="mw-list-item" id="n-portal"><a href="/wiki/Wikipedia:Community_portal" title="The hub for editors"><span>Community portal</span></a></li><li class="mw-list-item" id="n-recentchanges"><a accesskey="r" href="/wiki/Special:RecentChanges" title="A list of recent changes to Wikipedia [r]"><span>Recent changes</span></a></li><li class="mw-list-item" id="n-upload"><a href="/wiki/Wikipedia:File_upload_wizard" title="Add images or other media for use on Wikipedia"><span>Upload file</span></a></li><li class="mw-list-item" id="n-specialpages"><a accesskey="q" href="/wiki/Special:SpecialPages" title="A list of all special pages [q]"><span>Special pages</span></a></li>
</ul>
</div>
</div>
</div>
</div>
</div>
</div>
</nav>
<a class="mw-logo" href="/wiki/Main_Page">
<img alt="" aria-hidden="true" class="mw-logo-icon" height="50" src="/static/images/icons/enwiki-25.svg" width="50"/>
<span class="mw-logo-container skin-invert">
<img alt="Wikipedia" class="mw-logo-wordmark" src="/static/images/mobile/copyright/wikipedia-wordmark-en-25.svg" style="width: 8.75em; height: 1.375em;"/>
<img alt="The Free Encyclopedia" class="mw-logo-tagline" height="11" src="/static/images/mobile/copyright/wikipedia-tagline-en-25.svg" style="width: 8.75em; height: 0.6875em;" width="140"/>
</span>
</a>
</div>
<div class="vector-header-end">
<div class="vector-search-box-vue vector-search-box-collapses vector-search-box-show-thumbnail vector-search-box-auto-expand-width vector-search-box" id="p-search" role="search">
<a accesskey="f" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" href="/wiki/Special:Search" title="Search Wikipedia [f]"><span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search"></span>
<span>Search</span>
</a>
<div class="vector-typeahead-search-container">
<div class="cdx-typeahead-search cdx-typeahead-search--show-thumbnail cdx-typeahead-search--auto-expand-width">
<form action="/w/index.php" class="cdx-search-input cdx-search-input--has-end-button" id="searchform">
<div class="cdx-search-input__input-wrapper" data-search-loc="header-moved" id="simpleSearch">
<div class="cdx-text-input cdx-text-input--has-start-icon">
<input accesskey="f" aria-label="Search Wikipedia" autocapitalize="none" autocomplete="off" class="cdx-text-input__input mw-searchInput" id="searchInput" name="search" placeholder="Search Wikipedia" spellcheck="false" title="Search Wikipedia [f]" type="search"/>
<span class="cdx-text-input__icon cdx-text-input__start-icon"></span>
</div>
<input name="title" type="hidden" value="Special:Search"/>
</div>
<button class="cdx-button cdx-search-input__end-button">Search</button>
</form>
</div>
</div>
</div>
<nav aria-label="Personal tools" class="vector-user-links vector-user-links-wide">
<div class="vector-user-links-main">
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-preferences">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-userpage">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<nav aria-label="Appearance" class="vector-appearance-landmark">
<div class="vector-dropdown" id="vector-appearance-dropdown" title="Change the appearance of the page's font size, width, and color">
<input aria-haspopup="true" aria-label="Appearance" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-appearance-dropdown" id="vector-appearance-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-appearance-dropdown-checkbox" id="vector-appearance-dropdown-label"><span class="vector-icon mw-ui-icon-appearance mw-ui-icon-wikimedia-appearance"></span>
<span class="vector-dropdown-label-text">Appearance</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-unpinned-container" id="vector-appearance-unpinned-container">
</div>
</div>
</div>
</nav>
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-notifications">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<div class="vector-menu mw-portlet" id="p-vector-user-menu-overflow">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-sitesupport-2"><a class="" data-mw-interface="" href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en"><span>Donate</span></a>
</li>
<li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-createaccount-2"><a class="" data-mw-interface="" href="/w/index.php?title=Special:CreateAccount&amp;returnto=List+of+Indians+by+net+worth" title="You are encouraged to create an account and log in; however, it is not mandatory"><span>Create account</span></a>
</li>
<li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-login-2"><a accesskey="o" class="" data-mw-interface="" href="/w/index.php?title=Special:UserLogin&amp;returnto=List+of+Indians+by+net+worth" title="You're encouraged to log in; however, it's not mandatory. [o]"><span>Log in</span></a>
</li>
</ul>
</div>
</div>
</div>
<div class="vector-dropdown vector-user-menu vector-button-flush-right vector-user-menu-logged-out user-links-collapsible-item" id="vector-user-links-dropdown" title="Log in and more options">
<input aria-haspopup="true" aria-label="Personal tools" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-user-links-dropdown" id="vector-user-links-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-user-links-dropdown-checkbox" id="vector-user-links-dropdown-label"><span class="vector-icon mw-ui-icon-ellipsis mw-ui-icon-wikimedia-ellipsis"></span>
<span class="vector-dropdown-label-text">Personal tools</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-menu mw-portlet mw-portlet-personal user-links-collapsible-item" id="p-personal" title="User menu">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="user-links-collapsible-item mw-list-item" id="pt-sitesupport"><a href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en"><span>Donate</span></a></li><li class="user-links-collapsible-item mw-list-item" id="pt-createaccount"><a href="/w/index.php?title=Special:CreateAccount&amp;returnto=List+of+Indians+by+net+worth" title="You are encouraged to create an account and log in; however, it is not mandatory"><span class="vector-icon mw-ui-icon-userAdd mw-ui-icon-wikimedia-userAdd"></span> <span>Create account</span></a></li><li class="user-links-collapsible-item mw-list-item" id="pt-login"><a accesskey="o" href="/w/index.php?title=Special:UserLogin&amp;returnto=List+of+Indians+by+net+worth" title="You're encouraged to log in; however, it's not mandatory. [o]"><span class="vector-icon mw-ui-icon-logIn mw-ui-icon-wikimedia-logIn"></span> <span>Log in</span></a></li>
</ul>
</div>
</div>
</div>
</div>
</nav>
</div>
</header>
</div>
<div class="mw-page-container">
<div class="mw-page-container-inner">
<div class="vector-sitenotice-container">
<div id="siteNotice"><!-- CentralNotice --></div>
</div>
<div class="vector-column-start">
<div class="vector-main-menu-container">
<div id="mw-navigation">
<nav aria-label="Site" class="vector-main-menu-landmark" id="mw-panel">
<div class="vector-pinned-container" id="vector-main-menu-pinned-container">
</div>
</nav>
</div>
</div>
<div class="vector-sticky-pinned-container">
<nav aria-label="Contents" class="mw-table-of-contents-container vector-toc-landmark" data-event-name="ui.sidebar-toc" id="mw-panel-toc">
<div class="vector-pinned-container" id="vector-toc-pinned-container">
<div class="vector-toc vector-pinnable-element" id="vector-toc">

In [4]:
tdata = soup.find_all(class_="wikitable sortable")
len(tdata)

2

In [5]:
all_richest = tdata[0]
all_richest

<table class="wikitable sortable">
<tbody><tr>
<th>Rank
</th>
<th>Name
</th>
<th>Wealth
<p>Change
</p>
</th>
<th><a href="/wiki/Net_worth" title="Net worth">Net worth</a> (<a class="mw-redirect" href="/wiki/USD" title="USD">USD</a>)
</th>
<th>Company
</th>
<th>Sources of wealth
</th></tr>
<tr>
<td>1
</td>
<td><a href="/wiki/Mukesh_Ambani" title="Mukesh Ambani">Mukesh Ambani</a>
</td>
<td><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span>
</td>
<td>116 billion
</td>
<td><a href="/wiki/Reliance_Industries" title="Reliance Industries">Reliance Industries</a>
</td>
<td>Diversified
</td></tr>
<tr>
<td>2
</td>
<td><a href="/wiki/Gautam_Adani" title="Gautam Adani">Gautam Adani</a>
</td>
<td><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span>
</td>
<td>84 billion
</td>
<td><a href="/wiki/Adani_Group" title="Adani Group">Adani Group</a>
</td>
<td>Diversified
</td></tr>
<tr>
<td>3
</td>
<td><a href="/wiki/Shiv_Nadar" title="Shiv Nadar">Shiv Nadar</a>
</td>
<td><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span>
</td>
<td>36.9 billion
</td>
<td><a class="mw-redirect" href="/wiki/HCL_Technologies" title="HCL Technologies">HCL Technologies</a>
</td>
<td>IT services and consulting
</td></tr>
<tr>
<td>4
</td>
<td><a href="/wiki/Savitri_Jindal" title="Savitri Jindal">Savitri Jindal</a>
</td>
<td><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span>
</td>
<td>33.5 billion
</td>
<td><a href="/wiki/JSW_Group" title="JSW Group">JSW Group</a>
<p><a class="mw-redirect" href="/wiki/Jindal_Steel_and_Power" title="Jindal Steel and Power">Jindal Steel &amp; Power</a>
</p><p><a class="mw-redirect" href="/wiki/Jindal_Stainless_Limited" title="Jindal Stainless Limited">Jindal Stainless Limited</a>
</p>
</td>
<td>Steel, energy, cement and infrastructure
</td></tr>
<tr>
<td>5
</td>
<td><a href="/wiki/Dilip_Shanghvi" title="Dilip Shanghvi">Dilip Shanghvi</a>
</td>
<td><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span>
</td>
<td>26.7 billion
</td>
<td><a href="/wiki/Sun_Pharma" title="Sun Pharma">Sun Pharmaceutical Industries</a>
</td>
<td>Pharmaceuticals
</td></tr>
<tr>
<td>6
</td>
<td><a class="mw-redirect" href="/wiki/Cyrus_Poonawalla" title="Cyrus Poonawalla">Cyrus Poonawalla</a>
</td>
<td><span typeof="mw:File"><span title="Decrease"><img alt="Decrease" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/20px-Decrease2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/40px-Decrease2.svg.png 2x" width="11"/></span></span>
</td>
<td>21.3 billion
</td>
<td><a href="/wiki/Serum_Institute_of_India" title="Serum Institute of India">Serum Institute of India</a>
</td>
<td>Vaccines
</td></tr>
<tr>
<td>7
</td>
<td><a href="/wiki/Kushal_Pal_Singh" title="Kushal Pal Singh">Kushal Pal Singh</a>
</td>
<td><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span>
</td>
<td>20.9 billion
</td>
<td><a href="/wiki/DLF_(company)" title="DLF (company)">DLF</a>
</td>
<td>Real estate
</td></tr>
<tr>
<td>8
</td>
<td><a href="/wiki/Kumar_Mangalam_Birla" title="Kumar Mangalam Birla">Kumar Mangalam Birla</a>
</td>
<td><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span>
</td>
<td>19.7 billion
</td>
<td><a href="/wiki/Aditya_Birla_Group" title="Aditya Birla Group">Aditya Birla Group</a>
</td>
<td>Textiles, telecom, cement
</td></tr>
<tr>
<td>9
</td>
<td><a href="/wiki/Radhakishan_Damani" title="Radhakishan Damani">Radhakishan Damani</a>
</td>
<td><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span>
</td>
<td>17.6 billion
</td>
<td><a href="/wiki/DMart" title="DMart">Avenue Supermarts</a>, <a href="/wiki/DMart" title="DMart">DMart</a>
</td>
<td>Investments, retail
</td></tr>
<tr>
<td>10
</td>
<td><a class="mw-redirect" href="/wiki/Lakshmi_Mittal" title="Lakshmi Mittal">Lakshmi Mittal</a>
</td>
<td><span typeof="mw:File"><span title="Decrease"><img alt="Decrease" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/20px-Decrease2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/40px-Decrease2.svg.png 2x" width="11"/></span></span>
</td>
<td>16.4 billion
</td>
<td><a href="/wiki/ArcelorMittal" title="ArcelorMittal">ArcelorMittal</a>
</td>
<td>Steel
</td></tr>
<tr>
<td>11
</td>
<td><a href="/wiki/Ravi_Jaipuria" title="Ravi Jaipuria">Ravi Jaipuria</a>
</td>
<td><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span>
</td>
<td>16.2 billion
</td>
<td>RJ Corp
</td>
<td>Fast food
</td></tr>
<tr>
<td>12
</td>
<td><a href="/wiki/Uday_Kotak" title="Uday Kotak">Uday Kotak</a>
</td>
<td><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span>
</td>
<td>13.3 billion
</td>
<td><a href="/wiki/Kotak_Mahindra_Bank" title="Kotak Mahindra Bank">Kotak Mahindra Bank</a>
</td>
<td>Banking
</td></tr>
<tr>
<td>13
</td>
<td><a href="/wiki/Azim_Premji" title="Azim Premji">Azim Premji</a>
</td>
<td><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span>
</td>
<td>12.0 billion
</td>
<td><a href="/wiki/Wipro" title="Wipro">Wipro Group</a>
</td>
<td>IT services and consulting
</td></tr>
<tr>
<td>14
</td>
<td><a href="/wiki/Mangal_Lodha" title="Mangal Lodha">Mangal Lodha</a>
</td>
<td><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span>
</td>
<td>10.4 billion
</td>
<td><a href="/wiki/Lodha_Group" title="Lodha Group">Lodha Group</a>
</td>
<td>Real Estate
</td></tr>
<tr>
<td>15
</td>
<td><a href="/wiki/Pankaj_Patel" title="Pankaj Patel">Pankaj Patel</a>
</td>
<td><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span>
</td>
<td>9.5 billion
</td>
<td><a href="/wiki/Zydus_Lifesciences" title="Zydus Lifesciences">Zydus Lifesciences</a>
</td>
<td>Pharmaceuticals
</td></tr>
<tr>
<td>16
</td>
<td><a href="/wiki/Sunil_Mittal" title="Sunil Mittal">Sunil Mittal</a>
</td>
<td><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span>
</td>
<td>9.2 billion
</td>
<td><a href="/wiki/Bharti_Enterprises" title="Bharti Enterprises">Bharti Enterprises</a>
</td>
<td>Telecom
</td></tr>
<tr>
<td>17
</td>
<td><a class="new" href="/w/index.php?title=Rekha_Jhunjhunwala&amp;action=edit&amp;redlink=1" title="Rekha Jhunjhunwala (page does not exist)">Rekha Jhunjhunwala</a>
</td>
<td><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span>
</td>
<td>8.5 billion
</td>
<td>Rare Enterprises
</td>
<td>Investments
</td></tr>
<tr>
<td>18
</td>
<td><a class="new" href="/w/index.php?title=Hasmukh_Chudgar&amp;action=edit&amp;redlink=1" title="Hasmukh Chudgar (page does not exist)">Hasmukh Chudgar</a> &amp; family
</td>
<td><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span>
</td>
<td>7.7 billion
</td>
<td><a href="/wiki/Intas_Pharmaceuticals" title="Intas Pharmaceuticals">Intas Pharmaceuticals</a>
</td>
<td>Pharmaceuticals
</td></tr>
<tr>
<td>19
</td>
<td><a href="/wiki/M._A._Yusuff_Ali" title="M. A. Yusuff Ali">M. A. Yusuff Ali</a>
</td>
<td><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span>
</td>
<td>7.6 billion
</td>
<td><a href="/wiki/LuLu_Group_International" title="LuLu Group International">LuLu Group International</a>
</td>
<td>Retail
</td></tr>
<tr>
<td>20
</td>
<td><a class="new" href="/w/index.php?title=Gopikishan_Damani&amp;action=edit&amp;redlink=1" title="Gopikishan Damani (page does not exist)">Gopikishan Damani</a> &amp; family
</td>
<td><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span>
</td>
<td>7.0 billion
</td>
<td><a href="/wiki/DMart" title="DMart">Avenue Supermarts</a>, <a href="/wiki/DMart" title="DMart">DMart</a>
</td>
<td>Investments, retail
</td></tr>
<tr>
<td>21
</td>
<td><a href="/wiki/Benu_Gopal_Bangur" title="Benu Gopal Bangur">Benu Gopal Bangur</a>
</td>
<td><span typeof="mw:File"><span title="Decrease"><img alt="Decrease" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/20px-Decrease2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/40px-Decrease2.svg.png 2x" width="11"/></span></span>
</td>
<td>6.8 billion
</td>
<td><a href="/wiki/Shree_Cement" title="Shree Cement">Shree Cement</a>
</td>
<td>Cement
</td></tr>
<tr>
<td>22
</td>
<td><a href="/wiki/Vikram_Lal" title="Vikram Lal">Vikram Lal</a>
</td>
<td><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span>
</td>
<td>6.7 billion
</td>
<td><a href="/wiki/Eicher_Motors" title="Eicher Motors">Eicher Motors</a>
</td>
<td>Automotive
</td></tr>
<tr>
<td>23
</td>
<td><a class="new" href="/w/index.php?title=Murali_Divi&amp;action=edit&amp;redlink=1" title="Murali Divi (page does not exist)">Murali Divi</a> &amp; family
</td>
<td><span typeof="mw:File"><span title="Decrease"><img alt="Decrease" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/20px-Decrease2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/40px-Decrease2.svg.png 2x" width="11"/></span></span>
</td>
<td>6.2 billion
</td>
<td><a href="/wiki/Divi%27s_Laboratories" title="Divi's Laboratories">Divi's Laboratories</a>
</td>
<td>Pharmaceuticals
</td></tr>
<tr>
<td>24
</td>
<td><a href="/wiki/Rajan_Mittal" title="Rajan Mittal">Rajan Mittal</a>
</td>
<td><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span>
</td>
<td>6.0 billion
</td>
<td><a href="/wiki/Bharti_Enterprises" title="Bharti Enterprises">Bharti Enterprises</a>
</td>
<td>Telecom
</td></tr>
<tr>
<td>24
</td>
<td><a class="new" href="/w/index.php?title=Rakesh_Mittal&amp;action=edit&amp;redlink=1" title="Rakesh Mittal (page does not exist)">Rakesh Mittal</a>
</td>
<td><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span>
</td>
<td>6.0 billion
</td>
<td><a href="/wiki/Bharti_Enterprises" title="Bharti Enterprises">Bharti Enterprises</a>
</td>
<td>Telecom
</td></tr></tbody></table>

In [6]:
heads = [h.get_text().strip().replace('\n', ' ') for h in all_richest.find_all('th')]
heads

['Rank',
 'Name',
 'Wealth Change',
 'Net worth (USD)',
 'Company',
 'Sources of wealth']

In [7]:
data = all_richest.find_all('tr')[1:]
data

[<tr>
 <td>1
 </td>
 <td><a href="/wiki/Mukesh_Ambani" title="Mukesh Ambani">Mukesh Ambani</a>
 </td>
 <td><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span>
 </td>
 <td>116 billion
 </td>
 <td><a href="/wiki/Reliance_Industries" title="Reliance Industries">Reliance Industries</a>
 </td>
 <td>Diversified
 </td></tr>,
 <tr>
 <td>2
 </td>
 <td><a href="/wiki/Gautam_Adani" title="Gautam Adani">Gautam Adani</a>
 </td>
 <td><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span>
 </td>
 <td>84 billion
 </td>
 <td><a href="/wiki/Adani_Group" title="Adani Group">Adani Group</a>
 </td>
 <td>Diversified
 </td></tr>,
 <tr>
 <td>3
 </td>
 <td><a href="/wiki/Shiv_Nadar" title="Shiv Nadar">Shiv Nadar</a>
 </td>
 <td><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span>
 </td>
 <td>36.9 billion
 </td>
 <td><a class="mw-redirect" href="/wiki/HCL_Technologies" title="HCL Technologies">HCL Technologies</a>
 </td>
 <td>IT services and consulting
 </td></tr>,
 <tr>
 <td>4
 </td>
 <td><a href="/wiki/Savitri_Jindal" title="Savitri Jindal">Savitri Jindal</a>
 </td>
 <td><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span>
 </td>
 <td>33.5 billion
 </td>
 <td><a href="/wiki/JSW_Group" title="JSW Group">JSW Group</a>
 <p><a class="mw-redirect" href="/wiki/Jindal_Steel_and_Power" title="Jindal Steel and Power">Jindal Steel &amp; Power</a>
 </p><p><a class="mw-redirect" href="/wiki/Jindal_Stainless_Limited" title="Jindal Stainless Limited">Jindal Stainless Limited</a>
 </p>
 </td>
 <td>Steel, energy, cement and infrastructure
 </td></tr>,
 <tr>
 <td>5
 </td>
 <td><a href="/wiki/Dilip_Shanghvi" title="Dilip Shanghvi">Dilip Shanghvi</a>
 </td>
 <td><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span>
 </td>
 <td>26.7 billion
 </td>
 <td><a href="/wiki/Sun_Pharma" title="Sun Pharma">Sun Pharmaceutical Industries</a>
 </td>
 <td>Pharmaceuticals
 </td></tr>,
 <tr>
 <td>6
 </td>
 <td><a class="mw-redirect" href="/wiki/Cyrus_Poonawalla" title="Cyrus Poonawalla">Cyrus Poonawalla</a>
 </td>
 <td><span typeof="mw:File"><span title="Decrease"><img alt="Decrease" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/20px-Decrease2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/40px-Decrease2.svg.png 2x" width="11"/></span></span>
 </td>
 <td>21.3 billion
 </td>
 <td><a href="/wiki/Serum_Institute_of_India" title="Serum Institute of India">Serum Institute of India</a>
 </td>
 <td>Vaccines
 </td></tr>,
 <tr>
 <td>7
 </td>
 <td><a href="/wiki/Kushal_Pal_Singh" title="Kushal Pal Singh">Kushal Pal Singh</a>
 </td>
 <td><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span>
 </td>
 <td>20.9 billion
 </td>
 <td><a href="/wiki/DLF_(company)" title="DLF (company)">DLF</a>
 </td>
 <td>Real estate
 </td></tr>,
 <tr>
 <td>8
 </td>
 <td><a href="/wiki/Kumar_Mangalam_Birla" title="Kumar Mangalam Birla">Kumar Mangalam Birla</a>
 </td>
 <td><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span>
 </td>
 <td>19.7 billion
 </td>
 <td><a href="/wiki/Aditya_Birla_Group" title="Aditya Birla Group">Aditya Birla Group</a>
 </td>
 <td>Textiles, telecom, cement
 </td></tr>,
 <tr>
 <td>9
 </td>
 <td><a href="/wiki/Radhakishan_Damani" title="Radhakishan Damani">Radhakishan Damani</a>
 </td>
 <td><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span>
 </td>
 <td>17.6 billion
 </td>
 <td><a href="/wiki/DMart" title="DMart">Avenue Supermarts</a>, <a href="/wiki/DMart" title="DMart">DMart</a>
 </td>
 <td>Investments, retail
 </td></tr>,
 <tr>
 <td>10
 </td>
 <td><a class="mw-redirect" href="/wiki/Lakshmi_Mittal" title="Lakshmi Mittal">Lakshmi Mittal</a>
 </td>
 <td><span typeof="mw:File"><span title="Decrease"><img alt="Decrease" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/20px-Decrease2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/40px-Decrease2.svg.png 2x" width="11"/></span></span>
 </td>
 <td>16.4 billion
 </td>
 <td><a href="/wiki/ArcelorMittal" title="ArcelorMittal">ArcelorMittal</a>
 </td>
 <td>Steel
 </td></tr>,
 <tr>
 <td>11
 </td>
 <td><a href="/wiki/Ravi_Jaipuria" title="Ravi Jaipuria">Ravi Jaipuria</a>
 </td>
 <td><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span>
 </td>
 <td>16.2 billion
 </td>
 <td>RJ Corp
 </td>
 <td>Fast food
 </td></tr>,
 <tr>
 <td>12
 </td>
 <td><a href="/wiki/Uday_Kotak" title="Uday Kotak">Uday Kotak</a>
 </td>
 <td><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span>
 </td>
 <td>13.3 billion
 </td>
 <td><a href="/wiki/Kotak_Mahindra_Bank" title="Kotak Mahindra Bank">Kotak Mahindra Bank</a>
 </td>
 <td>Banking
 </td></tr>,
 <tr>
 <td>13
 </td>
 <td><a href="/wiki/Azim_Premji" title="Azim Premji">Azim Premji</a>
 </td>
 <td><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span>
 </td>
 <td>12.0 billion
 </td>
 <td><a href="/wiki/Wipro" title="Wipro">Wipro Group</a>
 </td>
 <td>IT services and consulting
 </td></tr>,
 <tr>
 <td>14
 </td>
 <td><a href="/wiki/Mangal_Lodha" title="Mangal Lodha">Mangal Lodha</a>
 </td>
 <td><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span>
 </td>
 <td>10.4 billion
 </td>
 <td><a href="/wiki/Lodha_Group" title="Lodha Group">Lodha Group</a>
 </td>
 <td>Real Estate
 </td></tr>,
 <tr>
 <td>15
 </td>
 <td><a href="/wiki/Pankaj_Patel" title="Pankaj Patel">Pankaj Patel</a>
 </td>
 <td><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span>
 </td>
 <td>9.5 billion
 </td>
 <td><a href="/wiki/Zydus_Lifesciences" title="Zydus Lifesciences">Zydus Lifesciences</a>
 </td>
 <td>Pharmaceuticals
 </td></tr>,
 <tr>
 <td>16
 </td>
 <td><a href="/wiki/Sunil_Mittal" title="Sunil Mittal">Sunil Mittal</a>
 </td>
 <td><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span>
 </td>
 <td>9.2 billion
 </td>
 <td><a href="/wiki/Bharti_Enterprises" title="Bharti Enterprises">Bharti Enterprises</a>
 </td>
 <td>Telecom
 </td></tr>,
 <tr>
 <td>17
 </td>
 <td><a class="new" href="/w/index.php?title=Rekha_Jhunjhunwala&amp;action=edit&amp;redlink=1" title="Rekha Jhunjhunwala (page does not exist)">Rekha Jhunjhunwala</a>
 </td>
 <td><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span>
 </td>
 <td>8.5 billion
 </td>
 <td>Rare Enterprises
 </td>
 <td>Investments
 </td></tr>,
 <tr>
 <td>18
 </td>
 <td><a class="new" href="/w/index.php?title=Hasmukh_Chudgar&amp;action=edit&amp;redlink=1" title="Hasmukh Chudgar (page does not exist)">Hasmukh Chudgar</a> &amp; family
 </td>
 <td><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span>
 </td>
 <td>7.7 billion
 </td>
 <td><a href="/wiki/Intas_Pharmaceuticals" title="Intas Pharmaceuticals">Intas Pharmaceuticals</a>
 </td>
 <td>Pharmaceuticals
 </td></tr>,
 <tr>
 <td>19
 </td>
 <td><a href="/wiki/M._A._Yusuff_Ali" title="M. A. Yusuff Ali">M. A. Yusuff Ali</a>
 </td>
 <td><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span>
 </td>
 <td>7.6 billion
 </td>
 <td><a href="/wiki/LuLu_Group_International" title="LuLu Group International">LuLu Group International</a>
 </td>
 <td>Retail
 </td></tr>,
 <tr>
 <td>20
 </td>
 <td><a class="new" href="/w/index.php?title=Gopikishan_Damani&amp;action=edit&amp;redlink=1" title="Gopikishan Damani (page does not exist)">Gopikishan Damani</a> &amp; family
 </td>
 <td><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span>
 </td>
 <td>7.0 billion
 </td>
 <td><a href="/wiki/DMart" title="DMart">Avenue Supermarts</a>, <a href="/wiki/DMart" title="DMart">DMart</a>
 </td>
 <td>Investments, retail
 </td></tr>,
 <tr>
 <td>21
 </td>
 <td><a href="/wiki/Benu_Gopal_Bangur" title="Benu Gopal Bangur">Benu Gopal Bangur</a>
 </td>
 <td><span typeof="mw:File"><span title="Decrease"><img alt="Decrease" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/20px-Decrease2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/40px-Decrease2.svg.png 2x" width="11"/></span></span>
 </td>
 <td>6.8 billion
 </td>
 <td><a href="/wiki/Shree_Cement" title="Shree Cement">Shree Cement</a>
 </td>
 <td>Cement
 </td></tr>,
 <tr>
 <td>22
 </td>
 <td><a href="/wiki/Vikram_Lal" title="Vikram Lal">Vikram Lal</a>
 </td>
 <td><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span>
 </td>
 <td>6.7 billion
 </td>
 <td><a href="/wiki/Eicher_Motors" title="Eicher Motors">Eicher Motors</a>
 </td>
 <td>Automotive
 </td></tr>,
 <tr>
 <td>23
 </td>
 <td><a class="new" href="/w/index.php?title=Murali_Divi&amp;action=edit&amp;redlink=1" title="Murali Divi (page does not exist)">Murali Divi</a> &amp; family
 </td>
 <td><span typeof="mw:File"><span title="Decrease"><img alt="Decrease" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/20px-Decrease2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/40px-Decrease2.svg.png 2x" width="11"/></span></span>
 </td>
 <td>6.2 billion
 </td>
 <td><a href="/wiki/Divi%27s_Laboratories" title="Divi's Laboratories">Divi's Laboratories</a>
 </td>
 <td>Pharmaceuticals
 </td></tr>,
 <tr>
 <td>24
 </td>
 <td><a href="/wiki/Rajan_Mittal" title="Rajan Mittal">Rajan Mittal</a>
 </td>
 <td><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span>
 </td>
 <td>6.0 billion
 </td>
 <td><a href="/wiki/Bharti_Enterprises" title="Bharti Enterprises">Bharti Enterprises</a>
 </td>
 <td>Telecom
 </td></tr>,
 <tr>
 <td>24
 </td>
 <td><a class="new" href="/w/index.php?title=Rakesh_Mittal&amp;action=edit&amp;redlink=1" title="Rakesh Mittal (page does not exist)">Rakesh Mittal</a>
 </td>
 <td><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span>
 </td>
 <td>6.0 billion
 </td>
 <td><a href="/wiki/Bharti_Enterprises" title="Bharti Enterprises">Bharti Enterprises</a>
 </td>
 <td>Telecom
 </td></tr>]

In [8]:
rank, name, wc, nw, comp, sow = ([],[],[],[],[],[])

for d in data:
    res = d.find_all('td')
    rank.append(res[0].get_text().strip())
    name.append(res[1].get_text().strip())
    wc.append(res[2].find_all('span')[1]['title'])
    nw.append(res[3].get_text().strip())
    comp.append(res[4].get_text().strip())
    sow.append(res[5].get_text())
print(len(rank), len(name), len(wc), len(nw), len(comp), len(sow))

25 25 25 25 25 25

In [9]:
df = pd.DataFrame({'Rank':rank, 'Name':name, 'Wealth Change':wc, 'Net Worth':nw, 'Company':comp,'Sources of Wealth':sow})
df

,Rank,Name,Wealth Change,Net Worth,Company,Sources of Wealth
0,1,Mukesh Ambani,Increase,116 billion,Reliance Industries,Diversified\n
1,2,Gautam Adani,Increase,84 billion,Adani Group,Diversified\n
2,3,Shiv Nadar,Increase,36.9 billion,HCL Technologies,IT services and consulting\n
3,4,Savitri Jindal,Increase,33.5 billion,JSW Group\nJindal Steel & Power\nJindal Stainl...,"Steel, energy, cement and infrastructure\n"
4,5,Dilip Shanghvi,Increase,26.7 billion,Sun Pharmaceutical Industries,Pharmaceuticals\n
5,6,Cyrus Poonawalla,Decrease,21.3 billion,Serum Institute of India,Vaccines\n
6,7,Kushal Pal Singh,Increase,20.9 billion,DLF,Real estate\n
7,8,Kumar Mangalam Birla,Increase,19.7 billion,Aditya Birla Group,"Textiles, telecom, cement\n"
8,9,Radhakishan Damani,Increase,17.6 billion,"Avenue Supermarts, DMart","Investments, retail\n"
9,10,Lakshmi Mittal,Decrease,16.4 billion,ArcelorMittal,Steel\n
10,11,Ravi Jaipuria,Increase,16.2 billion,RJ Corp,Fast food\n
11,12,Uday Kotak,Increase,13.3 billion,Kotak Mahindra Bank,Banking\n
12,13,Azim Premji,Increase,12.0 billion,Wipro Group,IT services and consulting\n
13,14,Mangal Lodha,Increase,10.4 billion,Lodha Group,Real Estate\n
14,15,Pankaj Patel,Increase,9.5 billion,Zydus Lifesciences,Pharmaceuticals\n
15,16,Sunil Mittal,Increase,9.2 billion,Bharti Enterprises,Telecom\n
16,17,Rekha Jhunjhunwala,Increase,8.5 billion,Rare Enterprises,Investments\n
17,18,Hasmukh Chudgar & family,Increase,7.7 billion,Intas Pharmaceuticals,Pharmaceuticals\n
18,19,M. A. Yusuff Ali,Increase,7.6 billion,LuLu Group International,Retail\n
19,20,Gopikishan Damani & family,Increase,7.0 billion,"Avenue Supermarts, DMart","Investments, retail\n"
20,21,Benu Gopal Bangur,Decrease,6.8 billion,Shree Cement,Cement\n
21,22,Vikram Lal,Increase,6.7 billion,Eicher Motors,Automotive\n
22,23,Murali Divi & family,Decrease,6.2 billion,Divi's Laboratories,Pharmaceuticals\n
23,24,Rajan Mittal,Increase,6.0 billion,Bharti Enterprises,Telecom\n
24,24,Rakesh Mittal,Increase,6.0 billion,Bharti Enterprises,Telecom\n

---
# International Indian Film Academy Awards

In [29]:
url = "https://en.wikipedia.org/wiki/International_Indian_Film_Academy_Awards"
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.7559.134'}
 
page = requests.get(url, headers=headers)
soup = BeautifulSoup(page.content, 'html.parser')
soup

<!DOCTYPE html>

<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available" dir="ltr" lang="en">
<head>
<meta charset="utf-8"/>
<title>International Indian Film Academy Awards - Wikipedia</title>
<script>(function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available";var cookie=document.cookie.match(/(?:^|; )enwikimwclientpreferences=([^;]+)/);if(cookie){cookie[1].split('%2C').forEach(function(pref){className=className.replace(new RegExp('(^| )'+pref.replace(/-clientpref-\w+$|[^\w-]+/g,'')+'-clientpref-\\w+( |$)'),'$1'+pref+'$2');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"b75b24a0-c8e8-41cf-b9c7-c918ca6c4d60","wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"International_Indian_Film_Academy_Awards","wgTitle":"International Indian Film Academy Awards","wgCurRevisionId":1324043522,"wgRevisionId":1324043522,"wgArticleId":3992437,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["Articles with short description","Short description is different from Wikidata","Use dmy dates from October 2025","Use Indian English from June 2018","All Wikipedia articles written in Indian English","Commons category link is on Wikidata","Webarchive template wayback links","International Indian Film Academy Awards","Awards established in 2000","2000 establishments in India","2000 in Indian cinema"],"wgPageViewLanguage":"en","wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"International_Indian_Film_Academy_Awards","wgRelevantArticleId":3992437,"wgTempUserName":null,"wgIsProbablyEditable":true,"wgRelevantPageIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"wgNoticeProject":"wikipedia","wgFlaggedRevsParams":{"tags":{"status":{"levels":1}}},"wgConfirmEditCaptchaNeededForGenericEdit":"hcaptcha","wgConfirmEditHCaptchaVisualEditorOnLoadIntegrationEnabled":false,"wgConfirmEditHCaptchaSiteKey":"5d0c670e-a5f4-4258-ad16-1f42792c9c62","wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgPopupsFlags":0,"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":false,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":10000,"wgEditSubmitButtonLabelPublish":true,"wgVisualEditorPageIsDisambiguation":false,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":false,"wgVector2022LanguageInHeader":true,"wgULSisLanguageSelectorEmpty":false,"wgWikibaseItemId":"Q655089","wgCheckUserClientHintsHeadersJsApi":["brands","architecture","bitness","fullVersionList","mobile","model","platform","platformVersion"],"GEHomepageSuggestedEditsEnableTopics":true,"wgGESuggestedEditsTaskTypes":{"taskTypes":["copyedit","link-recommendation"],"unavailableTaskTypes":[]},"wgGETopicsMatchModeEnabled":false,"wgGELevelingUpEnabledForUser":false,"wgGEUseTestKitchenExtension":true,"wgMetricsPlatformUserExperiments":{"active_experiments":[],"overrides":[],"enrolled":[],"assigned":[],"subject_ids":[],"sampling_units":[],"coordinator":[]},"wgTestKitchenUserExperiments":{"active_experiments":[],"overrides":[],"enrolled":[],"assigned":[],"subject_ids":[],"sampling_units":[],"coordinator":[]}};
RLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.wikimediamessages.styles":"ready","ext.cite.styles":"ready","skins.vector.search.codex.styles":"ready","skins.vector.styles":"ready","skins.vector.icons":"ready","jquery.tablesorter.styles":"ready","jquery.makeCollapsible.styles":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","wikibase.client.init":"ready"};RLPAGEMODULES=["ext.cite.ux-enhancements","site","mediawiki.page.ready","jquery.tablesorter","jquery.makeCollapsible","mediawiki.toc","skins.vector.js","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.gadget.ReferenceTooltips","ext.gadget.switcher","ext.urlShortener.toolbar","ext.centralauth.centralautologin","mmv.bootstrap","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.echo.centralauth","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.interface","ext.cx.eventlogging.campaigns","ext.cx.uls.quick.actions","wikibase.client.vector-2022","wikibase.databox.fromWikidata","ext.checkUser.clientHints","ext.growthExperiments.SuggestedEditSession","ext.xLab","ext.testKitchen"];</script>
<script>(RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return["user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});
}];});});</script>
<link href="/w/load.php?lang=en&amp;modules=ext.cite.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediamessages.styles%7Cjquery.makeCollapsible.styles%7Cjquery.tablesorter.styles%7Cskins.vector.icons%2Cstyles%7Cskins.vector.search.codex.styles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<script async="" src="/w/load.php?lang=en&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector-2022"></script>
<meta content="" name="ResourceLoaderDynamicStyles"/>
<link href="/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<meta content="MediaWiki 1.46.0-wmf.15" name="generator"/>
<meta content="origin" name="referrer"/>
<meta content="origin-when-cross-origin" name="referrer"/>
<meta content="max-image-preview:standard" name="robots"/>
<meta content="telephone=no" name="format-detection"/>
<meta content="https://upload.wikimedia.org/wikipedia/en/9/91/IIFA_trophy.jpg" property="og:image"/>
<meta content="529" property="og:image:width"/>
<meta content="1200" property="og:image:height"/>
<meta content="width=1120" name="viewport"/>
<meta content="International Indian Film Academy Awards - Wikipedia" property="og:title"/>
<meta content="website" property="og:type"/>
<link href="//upload.wikimedia.org" rel="preconnect"/>
<link href="/w/index.php?title=International_Indian_Film_Academy_Awards&amp;action=edit" rel="alternate" title="Edit this page" type="application/x-wiki"/>
<link href="/static/apple-touch/wikipedia.png" rel="apple-touch-icon"/>
<link href="/static/favicon/wikipedia.ico" rel="icon"/>
<link href="/w/rest.php/v1/search" rel="search" title="Wikipedia (en)" type="application/opensearchdescription+xml"/>
<link href="//en.wikipedia.org/w/api.php?action=rsd" rel="EditURI" type="application/rsd+xml"/>
<link href="https://en.wikipedia.org/wiki/International_Indian_Film_Academy_Awards" rel="canonical"/>
<link href="https://creativecommons.org/licenses/by-sa/4.0/deed.en" rel="license"/>
<link href="/w/index.php?title=Special:RecentChanges&amp;feed=atom" rel="alternate" title="Wikipedia Atom feed" type="application/atom+xml"/>
<link href="//meta.wikimedia.org" rel="dns-prefetch">
<link href="auth.wikimedia.org" rel="dns-prefetch"/>
</link></head>
<body class="skin--responsive skin-vector skin-vector-search-vue mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject mw-editable page-International_Indian_Film_Academy_Awards rootpage-International_Indian_Film_Academy_Awards skin-vector-2022 action-view">
<div aria-live="polite" class="mw-aria-live-region" id="mw-aria-live-region"></div><a class="mw-jump-link" href="#bodyContent">Jump to content</a>
<div class="vector-header-container">
<header class="vector-header mw-header no-font-mode-scale">
<div class="vector-header-start">
<nav aria-label="Site" class="vector-main-menu-landmark">
<div class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right" id="vector-main-menu-dropdown" title="Main menu">
<input aria-haspopup="true" aria-label="Main menu" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-main-menu-dropdown" id="vector-main-menu-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-main-menu-dropdown-checkbox" id="vector-main-menu-dropdown-label"><span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu"></span>
<span class="vector-dropdown-label-text">Main menu</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-unpinned-container" id="vector-main-menu-unpinned-container">
<div class="vector-main-menu vector-pinnable-element" id="vector-main-menu">
<div class="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned" data-feature-name="main-menu-pinned" data-pinnable-element-id="vector-main-menu" data-pinned-container-id="vector-main-menu-pinned-container" data-unpinned-container-id="vector-main-menu-unpinned-container">
<div class="vector-pinnable-header-label">Main menu</div>
<button class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">move to sidebar</button>
<button class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">hide</button>
</div>
<div class="vector-menu mw-portlet mw-portlet-navigation" id="p-navigation">
<div class="vector-menu-heading">
		Navigation
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="n-mainpage-description"><a accesskey="z" href="/wiki/Main_Page" title="Visit the main page [z]"><span>Main page</span></a></li><li class="mw-list-item" id="n-contents"><a href="/wiki/Wikipedia:Contents" title="Guides to browsing Wikipedia"><span>Contents</span></a></li><li class="mw-list-item" id="n-currentevents"><a href="/wiki/Portal:Current_events" title="Articles related to current events"><span>Current events</span></a></li><li class="mw-list-item" id="n-randompage"><a accesskey="x" href="/wiki/Special:Random" title="Visit a randomly selected article [x]"><span>Random article</span></a></li><li class="mw-list-item" id="n-aboutsite"><a href="/wiki/Wikipedia:About" title="Learn about Wikipedia and how it works"><span>About Wikipedia</span></a></li><li class="mw-list-item" id="n-contactpage"><a href="//en.wikipedia.org/wiki/Wikipedia:Contact_us" title="How to contact Wikipedia"><span>Contact us</span></a></li>
</ul>
</div>
</div>
<div class="vector-menu mw-portlet mw-portlet-interaction" id="p-interaction">
<div class="vector-menu-heading">
		Contribute
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="n-help"><a href="/wiki/Help:Contents" title="Guidance on how to use and edit Wikipedia"><span>Help</span></a></li><li class="mw-list-item" id="n-introduction"><a href="/wiki/Help:Introduction" title="Learn how to edit Wikipedia"><span>Learn to edit</span></a></li><li class="mw-list-item" id="n-portal"><a href="/wiki/Wikipedia:Community_portal" title="The hub for editors"><span>Community portal</span></a></li><li class="mw-list-item" id="n-recentchanges"><a accesskey="r" href="/wiki/Special:RecentChanges" title="A list of recent changes to Wikipedia [r]"><span>Recent changes</span></a></li><li class="mw-list-item" id="n-upload"><a href="/wiki/Wikipedia:File_upload_wizard" title="Add images or other media for use on Wikipedia"><span>Upload file</span></a></li><li class="mw-list-item" id="n-specialpages"><a accesskey="q" href="/wiki/Special:SpecialPages" title="A list of all special pages [q]"><span>Special pages</span></a></li>
</ul>
</div>
</div>
</div>
</div>
</div>
</div>
</nav>
<a class="mw-logo" href="/wiki/Main_Page">
<img alt="" aria-hidden="true" class="mw-logo-icon" height="50" src="/static/images/icons/enwiki-25.svg" width="50"/>
<span class="mw-logo-container skin-invert">
<img alt="Wikipedia" class="mw-logo-wordmark" src="/static/images/mobile/copyright/wikipedia-wordmark-en-25.svg" style="width: 8.75em; height: 1.375em;"/>
<img alt="The Free Encyclopedia" class="mw-logo-tagline" height="11" src="/static/images/mobile/copyright/wikipedia-tagline-en-25.svg" style="width: 8.75em; height: 0.6875em;" width="140"/>
</span>
</a>
</div>
<div class="vector-header-end">
<div class="vector-search-box-vue vector-search-box-collapses vector-search-box-show-thumbnail vector-search-box-auto-expand-width vector-search-box" id="p-search" role="search">
<a accesskey="f" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" href="/wiki/Special:Search" title="Search Wikipedia [f]"><span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search"></span>
<span>Search</span>
</a>
<div class="vector-typeahead-search-container">
<div class="cdx-typeahead-search cdx-typeahead-search--show-thumbnail cdx-typeahead-search--auto-expand-width">
<form action="/w/index.php" class="cdx-search-input cdx-search-input--has-end-button" id="searchform">
<div class="cdx-search-input__input-wrapper" data-search-loc="header-moved" id="simpleSearch">
<div class="cdx-text-input cdx-text-input--has-start-icon">
<input accesskey="f" aria-label="Search Wikipedia" autocapitalize="none" autocomplete="off" class="cdx-text-input__input mw-searchInput" id="searchInput" name="search" placeholder="Search Wikipedia" spellcheck="false" title="Search Wikipedia [f]" type="search"/>
<span class="cdx-text-input__icon cdx-text-input__start-icon"></span>
</div>
<input name="title" type="hidden" value="Special:Search"/>
</div>
<button class="cdx-button cdx-search-input__end-button">Search</button>
</form>
</div>
</div>
</div>
<nav aria-label="Personal tools" class="vector-user-links vector-user-links-wide">
<div class="vector-user-links-main">
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-preferences">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-userpage">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<nav aria-label="Appearance" class="vector-appearance-landmark">
<div class="vector-dropdown" id="vector-appearance-dropdown" title="Change the appearance of the page's font size, width, and color">
<input aria-haspopup="true" aria-label="Appearance" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-appearance-dropdown" id="vector-appearance-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-appearance-dropdown-checkbox" id="vector-appearance-dropdown-label"><span class="vector-icon mw-ui-icon-appearance mw-ui-icon-wikimedia-appearance"></span>
<span class="vector-dropdown-label-text">Appearance</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-unpinned-container" id="vector-appearance-unpinned-container">
</div>
</div>
</div>
</nav>
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-notifications">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<div class="vector-menu mw-portlet" id="p-vector-user-menu-overflow">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-sitesupport-2"><a class="" data-mw-interface="" href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en"><span>Donate</span></a>
</li>
<li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-createaccount-2"><a class="" data-mw-interface="" href="/w/index.php?title=Special:CreateAccount&amp;returnto=International+Indian+Film+Academy+Awards" title="You are encouraged to create an account and log in; however, it is not mandatory"><span>Create account</span></a>
</li>
<li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-login-2"><a accesskey="o" class="" data-mw-interface="" href="/w/index.php?title=Special:UserLogin&amp;returnto=International+Indian+Film+Academy+Awards" title="You're encouraged to log in; however, it's not mandatory. [o]"><span>Log in</span></a>
</li>
</ul>
</div>
</div>
</div>
<div class="vector-dropdown vector-user-menu vector-button-flush-right vector-user-menu-logged-out user-links-collapsible-item" id="vector-user-links-dropdown" title="Log in and more options">
<input aria-haspopup="true" aria-label="Personal tools" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-user-links-dropdown" id="vector-user-links-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-user-links-dropdown-checkbox" id="vector-user-links-dropdown-label"><span class="vector-icon mw-ui-icon-ellipsis mw-ui-icon-wikimedia-ellipsis"></span>
<span class="vector-dropdown-label-text">Personal tools</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-menu mw-portlet mw-portlet-personal user-links-collapsible-item" id="p-personal" title="User menu">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="user-links-collapsible-item mw-list-item" id="pt-sitesupport"><a href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en"><span>Donate</span></a></li><li class="user-links-collapsible-item mw-list-item" id="pt-createaccount"><a href="/w/index.php?title=Special:CreateAccount&amp;returnto=International+Indian+Film+Academy+Awards" title="You are encouraged to create an account and log in; however, it is not mandatory"><span class="vector-icon mw-ui-icon-userAdd mw-ui-icon-wikimedia-userAdd"></span> <span>Create account</span></a></li><li class="user-links-collapsible-item mw-list-item" id="pt-login"><a accesskey="o" href="/w/index.php?title=Special:UserLogin&amp;returnto=International+Indian+Film+Academy+Awards" title="You're encouraged to log in; however, it's not mandatory. [o]"><span class="vector-icon mw-ui-icon-logIn mw-ui-icon-wikimedia-logIn"></span> <span>Log in</span></a></li>
</ul>
</div>
</div>
</div>
</div>
</nav>
</div>
</header>
</div>
<div class="mw-page-container">
<div class="mw-page-container-inner">
<div class="vector-sitenotice-container">

In [31]:
awards = soup.find(class_="sortable wikitable")
awards

<table class="sortable wikitable" style="text-align: center">
<caption>
</caption>
<tbody><tr>
<th>Ceremony
</th>
<th>Date
</th>
<th><a href="/wiki/IIFA_Award_for_Best_Film" title="IIFA Award for Best Film">Best Film</a>
</th>
<th>Host(s)
</th>
<th>Venue
</th>
<th>City, Country
</th></tr>
<tr>
<td><a href="/wiki/1st_IIFA_Awards" title="1st IIFA Awards">1st</a></td>
<td>24 June 2000</td>
<td><i><a href="/wiki/Hum_Dil_De_Chuke_Sanam" title="Hum Dil De Chuke Sanam">Hum Dil De Chuke Sanam</a> </i></td>
<td><a href="/wiki/Yukta_Mookhey" title="Yukta Mookhey">Yukta Mookhey</a> <br/><a href="/wiki/Anupam_Kher" title="Anupam Kher">Anupam Kher</a></td>
<td><a href="/wiki/Millennium_Dome" title="Millennium Dome">Millennium Dome</a></td>
<td><a href="/wiki/London" title="London">London</a>, United Kingdom
</td></tr>
<tr>
<td><a href="/wiki/2nd_IIFA_Awards" title="2nd IIFA Awards">2nd</a></td>
<td>16 June 2001</td>
<td><i><a href="/wiki/Kaho_Naa..._Pyaar_Hai" title="Kaho Naa... Pyaar Hai">Kaho Naa... Pyaar Hai</a> </i></td>
<td><a href="/wiki/Priyanka_Chopra" title="Priyanka Chopra">Priyanka Chopra</a><br/><a href="/wiki/Kabir_Bedi" title="Kabir Bedi">Kabir Bedi</a></td>
<td>Superbowl Arena</td>
<td><a class="mw-redirect" href="/wiki/Sun_City,_North_West" title="Sun City, North West">Sun City</a>, South Africa
</td></tr>
<tr>
<td><a href="/wiki/3rd_IIFA_Awards" title="3rd IIFA Awards">3rd</a></td>
<td>6 April 2002</td>
<td><i><a href="/wiki/Lagaan" title="Lagaan">Lagaan</a> </i></td>
<td><a href="/wiki/Lara_Dutta" title="Lara Dutta">Lara Dutta</a></td>
<td><a href="/wiki/Arena_of_Stars" title="Arena of Stars">Arena of Stars</a></td>
<td><a href="/wiki/Genting_Highlands" title="Genting Highlands">Genting Highlands</a>, Malaysia
</td></tr>
<tr>
<td><a href="/wiki/4th_IIFA_Awards" title="4th IIFA Awards">4th</a></td>
<td>17 May 2003</td>
<td><i><a href="/wiki/Devdas_(2002_Hindi_film)" title="Devdas (2002 Hindi film)">Devdas</a> </i></td>
<td><a href="/wiki/Anil_Kapoor" title="Anil Kapoor">Anil Kapoor</a><br/><a href="/wiki/Dia_Mirza" title="Dia Mirza">Dia Mirza</a></td>
<td><a class="mw-redirect" href="/wiki/Coca-Cola_Dome" title="Coca-Cola Dome">Coca-Cola Dome</a></td>
<td><a href="/wiki/Johannesburg" title="Johannesburg">Johannesburg</a>, South Africa
</td></tr>
<tr>
<td><a href="/wiki/5th_IIFA_Awards" title="5th IIFA Awards">5th</a></td>
<td>22 May 2004</td>
<td><i><a href="/wiki/Kal_Ho_Naa_Ho" title="Kal Ho Naa Ho">Kal Ho Naa Ho</a> </i></td>
<td><a href="/wiki/Rahul_Khanna" title="Rahul Khanna">Rahul Khanna</a></td>
<td><a href="/wiki/Singapore_Indoor_Stadium" title="Singapore Indoor Stadium">Singapore Indoor Stadium</a></td>
<td><a href="/wiki/Singapore" title="Singapore">Singapore</a>, Singapore
</td></tr>
<tr>
<td><a href="/wiki/6th_IIFA_Awards" title="6th IIFA Awards">6th</a></td>
<td>11 June 2005</td>
<td><i><a href="/wiki/Veer-Zaara" title="Veer-Zaara">Veer-Zaara</a> </i></td>
<td><a href="/wiki/Shah_Rukh_Khan" title="Shah Rukh Khan">Shahrukh Khan</a><br/><a href="/wiki/Fardeen_Khan" title="Fardeen Khan">Fardeen Khan</a><br/><a href="/wiki/Karan_Johar" title="Karan Johar">Karan Johar</a></td>
<td><a class="mw-redirect" href="/wiki/Amsterdam_Arena" title="Amsterdam Arena">Amsterdam Arena</a></td>
<td><a href="/wiki/Amsterdam" title="Amsterdam">Amsterdam</a>, Netherlands
</td></tr>
<tr>
<td><a href="/wiki/7th_IIFA_Awards" title="7th IIFA Awards">7th</a></td>
<td>17 June 2006</td>
<td><i><a href="/wiki/Black_(2005_film)" title="Black (2005 film)">Black</a> </i></td>
<td><a href="/wiki/Fardeen_Khan" title="Fardeen Khan">Fardeen Khan</a><br/><a href="/wiki/Lara_Dutta" title="Lara Dutta">Lara Dutta</a></td>
<td><a href="/wiki/Dubai_International_Convention_Centre" title="Dubai International Convention Centre">Dubai International Convention Centre</a></td>
<td><a href="/wiki/Dubai" title="Dubai">Dubai</a>, United Arab Emirates
</td></tr>
<tr>
<td><a href="/wiki/8th_IIFA_Awards" title="8th IIFA Awards">8th</a></td>
<td>9 June 2007</td>
<td><i><a href="/wiki/Rang_De_Basanti" title="Rang De Basanti">Rang De Basanti</a> </i></td>
<td><a href="/wiki/Boman_Irani" title="Boman Irani">Boman Irani</a><br/><a href="/wiki/Lara_Dutta" title="Lara Dutta">Lara Dutta</a></td>
<td><a class="mw-redirect" href="/wiki/Hallam_FM_Arena" title="Hallam FM Arena">Hallam FM Arena</a></td>
<td><a href="/wiki/Sheffield" title="Sheffield">Sheffield</a>, United Kingdom
</td></tr>
<tr>
<td><a href="/wiki/9th_IIFA_Awards" title="9th IIFA Awards">9th</a></td>
<td>8 June 2008</td>
<td><i><a href="/wiki/Chak_De!_India" title="Chak De! India">Chak De! India</a> </i></td>
<td><a href="/wiki/Boman_Irani" title="Boman Irani">Boman Irani</a><br/><a class="mw-redirect" href="/wiki/Ritesh_Deshmukh" title="Ritesh Deshmukh">Ritesh Deshmukh</a></td>
<td><a href="/wiki/Siam_Paragon" title="Siam Paragon">Siam Paragon</a></td>
<td><a href="/wiki/Bangkok" title="Bangkok">Bangkok</a>, Thailand
</td></tr>
<tr>
<td><a href="/wiki/10th_IIFA_Awards" title="10th IIFA Awards">10th</a></td>
<td>13 June 2009</td>
<td><i><a href="/wiki/Jodhaa_Akbar" title="Jodhaa Akbar">Jodhaa Akbar</a> </i></td>
<td rowspan="2"><a href="/wiki/Boman_Irani" title="Boman Irani">Boman Irani</a><br/><a class="mw-redirect" href="/wiki/Ritesh_Deshmukh" title="Ritesh Deshmukh">Ritesh Deshmukh</a><br/><a href="/wiki/Lara_Dutta" title="Lara Dutta">Lara Dutta</a></td>
<td><a href="/wiki/The_Venetian_Macao" title="The Venetian Macao">The Venetian Macao</a></td>
<td><a href="/wiki/Macau" title="Macau">Macau</a>, Macau
</td></tr>
<tr>
<td><a href="/wiki/11th_IIFA_Awards" title="11th IIFA Awards">11th</a></td>
<td>5 June 2010</td>
<td><i><a href="/wiki/3_Idiots" title="3 Idiots">3 Idiots</a> </i></td>
<td><a href="/wiki/Sugathadasa_Stadium" title="Sugathadasa Stadium">Sugathadasa Stadium</a></td>
<td><a href="/wiki/Colombo" title="Colombo">Colombo</a>, Sri Lanka
</td></tr>
<tr>
<td><a href="/wiki/12th_IIFA_Awards" title="12th IIFA Awards">12th</a></td>
<td>25 June 2011</td>
<td><i><a href="/wiki/Dabangg" title="Dabangg">Dabangg</a> </i></td>
<td><a href="/wiki/Boman_Irani" title="Boman Irani">Boman Irani</a><br/><a class="mw-redirect" href="/wiki/Ritesh_Deshmukh" title="Ritesh Deshmukh">Ritesh Deshmukh</a></td>
<td><a href="/wiki/Rogers_Centre" title="Rogers Centre">Rogers Centre</a></td>
<td><a href="/wiki/Toronto" title="Toronto">Toronto</a>, Canada
</td></tr>
<tr>
<td><a href="/wiki/13th_IIFA_Awards" title="13th IIFA Awards">13th</a></td>
<td>9 June 2012</td>
<td><i><a href="/wiki/Zindagi_Na_Milegi_Dobara" title="Zindagi Na Milegi Dobara">Zindagi Na Milegi Dobara</a> </i></td>
<td><a href="/wiki/Shahid_Kapoor" title="Shahid Kapoor">Shahid Kapoor</a><br/><a href="/wiki/Farhan_Akhtar" title="Farhan Akhtar">Farhan Akhtar</a></td>
<td><a href="/wiki/Singapore_Indoor_Stadium" title="Singapore Indoor Stadium">Singapore Indoor Stadium</a></td>
<td><a href="/wiki/Singapore" title="Singapore">Singapore</a>, Singapore
</td></tr>
<tr>
<td><a href="/wiki/14th_IIFA_Awards" title="14th IIFA Awards">14th</a></td>
<td>6 July 2013</td>
<td><i><a href="/wiki/Barfi!" title="Barfi!">Barfi!</a></i></td>
<td><a href="/wiki/Salman_Khan" title="Salman Khan">Salman Khan</a><br/><a href="/wiki/Akshay_Kumar" title="Akshay Kumar">Akshay Kumar</a></td>
<td><a href="/wiki/The_Venetian_Macao" title="The Venetian Macao">The Venetian Macao</a></td>
<td><a href="/wiki/Macau" title="Macau">Macau</a>, Macau
</td></tr>
<tr>
<td><a href="/wiki/15th_IIFA_Awards" title="15th IIFA Awards">15th</a></td>
<td>26 April 2014</td>
<td><i><a href="/wiki/Bhaag_Milkha_Bhaag" title="Bhaag Milkha Bhaag">Bhaag Milkha Bhaag</a></i></td>
<td><a href="/wiki/Shahid_Kapoor" title="Shahid Kapoor">Shahid Kapoor</a><br/><a href="/wiki/Farhan_Akhtar" title="Farhan Akhtar">Farhan Akhtar</a></td>
<td><a href="/wiki/Raymond_James_Stadium" title="Raymond James Stadium">Raymond James Stadium</a></td>
<td><a class="mw-redirect" href="/wiki/Tampa_Bay_Area" title="Tampa Bay Area">Tampa</a>, United States
</td></tr>
<tr>
<td><a href="/wiki/16th_IIFA_Awards" title="16th IIFA Awards">16th</a></td>
<td>7 June 2015</td>
<td><i><a class="mw-redirect" href="/wiki/Queen_(2014_film)" title="Queen (2014 film)">Queen</a></i></td>
<td><a href="/wiki/Arjun_Kapoor" title="Arjun Kapoor">Arjun Kapoor</a><br/><a href="/wiki/Ranveer_Singh" title="Ranveer Singh">Ranveer Singh</a></td>
<td><a class="mw-redirect" href="/wiki/Putra_Indoor_Stadium" title="Putra Indoor Stadium">Putra Indoor Stadium</a></td>
<td><a href="/wiki/Kuala_Lumpur" title="Kuala Lumpur">Kuala Lumpur</a>, Malaysia
</td></tr>
<tr>
<td><a href="/wiki/17th_IIFA_Awards" title="17th IIFA Awards">17th</a></td>
<td>25 June 2016</td>
<td><i><a href="/wiki/Bajrangi_Bhaijaan" title="Bajrangi Bhaijaan">Bajrangi Bhaijaan</a></i></td>
<td><a href="/wiki/Shahid_Kapoor" title="Shahid Kapoor">Shahid Kapoor</a><br/><a href="/wiki/Farhan_Akhtar" title="Farhan Akhtar">Farhan Akhtar</a><sup class="reference" id="cite_ref-4"><a href="#cite_note-4"><span class="cite-bracket">[</span>4<span class="cite-bracket">]</span></a></sup></td>
<td><a class="extiw" href="https://es.wikipedia.org/wiki/Ifema" title="es:Ifema">IFEMA</a></td>
<td><a href="/wiki/Madrid" title="Madrid">Madrid</a>, Spain
</td></tr>
<tr>
<td><a href="/wiki/18th_IIFA_Awards" title="18th IIFA Awards">18th</a>
</td>
<td>14–15 July 2017<sup class="reference" id="cite_ref-5"><a href="#cite_note-5"><span class="cite-bracket">[</span>5<span class="cite-bracket">]</span></a></sup>
</td>
<td><i><a href="/wiki/Neerja" title="Neerja">Neerja</a></i>
</td>
<td><a href="/wiki/Karan_Johar" title="Karan Johar">Karan Johar</a>
<p><a href="/wiki/Saif_Ali_Khan" title="Saif Ali Khan">Saif Ali Khan</a>
</p>
</td>
<td><a href="/wiki/MetLife_Stadium" title="MetLife Stadium">MetLife Stadium</a>
</td>
<td><a href="/wiki/East_Rutherford,_New_Jersey" title="East Rutherford, New Jersey">New Jersey</a>, United States
</td></tr>
<tr>
<td><a href="/wiki/19th_IIFA_Awards" title="19th IIFA Awards">19th</a></td>
<td>22–24 June 2018</td>
<td><i><a href="/wiki/Tumhari_Sulu" title="Tumhari Sulu">Tumhari Sulu</a></i></td>
<td><a href="/wiki/Karan_Johar" title="Karan Johar">Karan Johar</a><br/><a href="/wiki/Riteish_Deshmukh" title="Riteish Deshmukh">Riteish Deshmukh</a></td>
<td><a href="/wiki/Siam_Niramit" title="Siam Niramit">Siam Niramit Theatre</a></td>
<td><a href="/wiki/Bangkok" title="Bangkok">Bangkok</a>, Thailand
</td></tr>
<tr>
<td><a href="/wiki/20th_IIFA_Awards" title="20th IIFA Awards">20th</a></td>
<td>18 September 2019</td>
<td><i><a href="/wiki/Raazi" title="Raazi">Raazi</a></i></td>
<td><a href="/wiki/Ayushmann_Khurrana" title="Ayushmann Khurrana">Ayushmann Khurrana</a><br/><a href="/wiki/Aparshakti_Khurana" title="Aparshakti Khurana">Aparshakti Khurana</a></td>
<td><a href="/wiki/Sardar_Vallabhbhai_Patel_Indoor_Stadium" title="Sardar Vallabhbhai Patel Indoor Stadium">Sardar Vallabhbhai Patel Indoor Stadium</a></td>
<td><a href="/wiki/Mumbai" title="Mumbai">Mumbai</a>, India
</td></tr>
<tr>
<td><a href="/wiki/21st_IIFA_Awards" title="21st IIFA Awards">21st</a></td>
<td>24 November 2021</td>
<td><i><a href="/wiki/Kabir_Singh" title="Kabir Singh">Kabir Singh</a></i></td>
<td colspan="3">The ceremony was cancelled due to <a href="/wiki/COVID-19_pandemic" title="COVID-19 pandemic">COVID-19 pandemic</a>. The winners were announced through <a href="/wiki/Instagram" title="Instagram">Instagram</a>.
</td></tr>
<tr>
<td><a href="/wiki/22nd_IIFA_Awards" title="22nd IIFA Awards">22nd</a></td>
<td>2–4 June 2022</td>
<td><i><a href="/wiki/Shershaah" title="Shershaah">Shershaah</a></i></td>
<td><a href="/wiki/Salman_Khan" title="Salman Khan">Salman Khan</a> <br/><a href="/wiki/Riteish_Deshmukh" title="Riteish Deshmukh">Riteish Deshmukh</a><br/><a href="/wiki/Maniesh_Paul" title="Maniesh Paul">Maniesh Paul</a></td>
<td rowspan="3"><a href="/wiki/Etihad_Arena" title="Etihad Arena">Etihad Arena</a></td>
<td rowspan="3"><a href="/wiki/Abu_Dhabi" title="Abu Dhabi">Abu Dhabi</a>, United Arab Emirates
</td></tr>
<tr>
<td><a href="/wiki/23rd_IIFA_Awards" title="23rd IIFA Awards">23rd</a></td>
<td>26–27 May 2023</td>
<td><i><a href="/wiki/Drishyam_2" title="Drishyam 2">Drishyam 2</a></i></td>
<td><a href="/wiki/Vicky_Kaushal" title="Vicky Kaushal">Vicky Kaushal</a><br/><a href="/wiki/Abhishek_Bachchan" title="Abhishek Bachchan">Abhishek Bachchan</a>
</td></tr>
<tr>
<td><a href="/wiki/24th_IIFA_Awards" title="24th IIFA Awards">24th</a>
</td>
<td>28 September 2024
</td>
<td><i><a href="/wiki/Animal_(2023_Indian_film)" title="Animal (2023 Indian film)">Animal</a></i>
</td>
<td><a href="/wiki/Shah_Rukh_Khan" title="Shah Rukh Khan">Shah Rukh Khan</a><br/><a href="/wiki/Karan_Johar" title="Karan Johar">Karan Johar</a><br/><a href="/wiki/Vicky_Kaushal" title="Vicky Kaushal">Vicky Kaushal</a>
</td></tr>
<tr>
<td><a href="/wiki/25th_IIFA_Awards" title="25th IIFA Awards">25th</a>
</td>
<td>8–9 March 2025
</td>
<td><i><a href="/wiki/Laapataa_Ladies" title="Laapataa Ladies">Laapataa Ladies</a></i>
</td>
<td><a href="/wiki/Karan_Johar" title="Karan Johar">Karan Johar</a>, <a href="/wiki/Kartik_Aaryan" title="Kartik Aaryan">Kartik Aaryan</a>
</td>
<td>Jaipur Exhibition &amp; Convention Centre
</td>
<td><a href="/wiki/Jaipur" title="Jaipur">Jaipur</a>, India
</td></tr></tbody></table>

In [34]:
heads = [h.get_text().strip() for h in awards.find_all('th')]
heads

['Ceremony', 'Date', 'Best Film', 'Host(s)', 'Venue', 'City, Country']

In [35]:
tdata = awards.find_all('tr')[1:]
tdata

[<tr>
 <td><a href="/wiki/1st_IIFA_Awards" title="1st IIFA Awards">1st</a></td>
 <td>24 June 2000</td>
 <td><i><a href="/wiki/Hum_Dil_De_Chuke_Sanam" title="Hum Dil De Chuke Sanam">Hum Dil De Chuke Sanam</a> </i></td>
 <td><a href="/wiki/Yukta_Mookhey" title="Yukta Mookhey">Yukta Mookhey</a> <br/><a href="/wiki/Anupam_Kher" title="Anupam Kher">Anupam Kher</a></td>
 <td><a href="/wiki/Millennium_Dome" title="Millennium Dome">Millennium Dome</a></td>
 <td><a href="/wiki/London" title="London">London</a>, United Kingdom
 </td></tr>,
 <tr>
 <td><a href="/wiki/2nd_IIFA_Awards" title="2nd IIFA Awards">2nd</a></td>
 <td>16 June 2001</td>
 <td><i><a href="/wiki/Kaho_Naa..._Pyaar_Hai" title="Kaho Naa... Pyaar Hai">Kaho Naa... Pyaar Hai</a> </i></td>
 <td><a href="/wiki/Priyanka_Chopra" title="Priyanka Chopra">Priyanka Chopra</a><br/><a href="/wiki/Kabir_Bedi" title="Kabir Bedi">Kabir Bedi</a></td>
 <td>Superbowl Arena</td>
 <td><a class="mw-redirect" href="/wiki/Sun_City,_North_West" title="Sun City, North West">Sun City</a>, South Africa
 </td></tr>,
 <tr>
 <td><a href="/wiki/3rd_IIFA_Awards" title="3rd IIFA Awards">3rd</a></td>
 <td>6 April 2002</td>
 <td><i><a href="/wiki/Lagaan" title="Lagaan">Lagaan</a> </i></td>
 <td><a href="/wiki/Lara_Dutta" title="Lara Dutta">Lara Dutta</a></td>
 <td><a href="/wiki/Arena_of_Stars" title="Arena of Stars">Arena of Stars</a></td>
 <td><a href="/wiki/Genting_Highlands" title="Genting Highlands">Genting Highlands</a>, Malaysia
 </td></tr>,
 <tr>
 <td><a href="/wiki/4th_IIFA_Awards" title="4th IIFA Awards">4th</a></td>
 <td>17 May 2003</td>
 <td><i><a href="/wiki/Devdas_(2002_Hindi_film)" title="Devdas (2002 Hindi film)">Devdas</a> </i></td>
 <td><a href="/wiki/Anil_Kapoor" title="Anil Kapoor">Anil Kapoor</a><br/><a href="/wiki/Dia_Mirza" title="Dia Mirza">Dia Mirza</a></td>
 <td><a class="mw-redirect" href="/wiki/Coca-Cola_Dome" title="Coca-Cola Dome">Coca-Cola Dome</a></td>
 <td><a href="/wiki/Johannesburg" title="Johannesburg">Johannesburg</a>, South Africa
 </td></tr>,
 <tr>
 <td><a href="/wiki/5th_IIFA_Awards" title="5th IIFA Awards">5th</a></td>
 <td>22 May 2004</td>
 <td><i><a href="/wiki/Kal_Ho_Naa_Ho" title="Kal Ho Naa Ho">Kal Ho Naa Ho</a> </i></td>
 <td><a href="/wiki/Rahul_Khanna" title="Rahul Khanna">Rahul Khanna</a></td>
 <td><a href="/wiki/Singapore_Indoor_Stadium" title="Singapore Indoor Stadium">Singapore Indoor Stadium</a></td>
 <td><a href="/wiki/Singapore" title="Singapore">Singapore</a>, Singapore
 </td></tr>,
 <tr>
 <td><a href="/wiki/6th_IIFA_Awards" title="6th IIFA Awards">6th</a></td>
 <td>11 June 2005</td>
 <td><i><a href="/wiki/Veer-Zaara" title="Veer-Zaara">Veer-Zaara</a> </i></td>
 <td><a href="/wiki/Shah_Rukh_Khan" title="Shah Rukh Khan">Shahrukh Khan</a><br/><a href="/wiki/Fardeen_Khan" title="Fardeen Khan">Fardeen Khan</a><br/><a href="/wiki/Karan_Johar" title="Karan Johar">Karan Johar</a></td>
 <td><a class="mw-redirect" href="/wiki/Amsterdam_Arena" title="Amsterdam Arena">Amsterdam Arena</a></td>
 <td><a href="/wiki/Amsterdam" title="Amsterdam">Amsterdam</a>, Netherlands
 </td></tr>,
 <tr>
 <td><a href="/wiki/7th_IIFA_Awards" title="7th IIFA Awards">7th</a></td>
 <td>17 June 2006</td>
 <td><i><a href="/wiki/Black_(2005_film)" title="Black (2005 film)">Black</a> </i></td>
 <td><a href="/wiki/Fardeen_Khan" title="Fardeen Khan">Fardeen Khan</a><br/><a href="/wiki/Lara_Dutta" title="Lara Dutta">Lara Dutta</a></td>
 <td><a href="/wiki/Dubai_International_Convention_Centre" title="Dubai International Convention Centre">Dubai International Convention Centre</a></td>
 <td><a href="/wiki/Dubai" title="Dubai">Dubai</a>, United Arab Emirates
 </td></tr>,
 <tr>
 <td><a href="/wiki/8th_IIFA_Awards" title="8th IIFA Awards">8th</a></td>
 <td>9 June 2007</td>
 <td><i><a href="/wiki/Rang_De_Basanti" title="Rang De Basanti">Rang De Basanti</a> </i></td>
 <td><a href="/wiki/Boman_Irani" title="Boman Irani">Boman Irani</a><br/><a href="/wiki/Lara_Dutta" title="Lara Dutta">Lara Dutta</a></td>
 <td><a class="mw-redirect" href="/wiki/Hallam_FM_Arena" title="Hallam FM Arena">Hallam FM Arena</a></td>
 <td><a href="/wiki/Sheffield" title="Sheffield">Sheffield</a>, United Kingdom
 </td></tr>,
 <tr>
 <td><a href="/wiki/9th_IIFA_Awards" title="9th IIFA Awards">9th</a></td>
 <td>8 June 2008</td>
 <td><i><a href="/wiki/Chak_De!_India" title="Chak De! India">Chak De! India</a> </i></td>
 <td><a href="/wiki/Boman_Irani" title="Boman Irani">Boman Irani</a><br/><a class="mw-redirect" href="/wiki/Ritesh_Deshmukh" title="Ritesh Deshmukh">Ritesh Deshmukh</a></td>
 <td><a href="/wiki/Siam_Paragon" title="Siam Paragon">Siam Paragon</a></td>
 <td><a href="/wiki/Bangkok" title="Bangkok">Bangkok</a>, Thailand
 </td></tr>,
 <tr>
 <td><a href="/wiki/10th_IIFA_Awards" title="10th IIFA Awards">10th</a></td>
 <td>13 June 2009</td>
 <td><i><a href="/wiki/Jodhaa_Akbar" title="Jodhaa Akbar">Jodhaa Akbar</a> </i></td>
 <td rowspan="2"><a href="/wiki/Boman_Irani" title="Boman Irani">Boman Irani</a><br/><a class="mw-redirect" href="/wiki/Ritesh_Deshmukh" title="Ritesh Deshmukh">Ritesh Deshmukh</a><br/><a href="/wiki/Lara_Dutta" title="Lara Dutta">Lara Dutta</a></td>
 <td><a href="/wiki/The_Venetian_Macao" title="The Venetian Macao">The Venetian Macao</a></td>
 <td><a href="/wiki/Macau" title="Macau">Macau</a>, Macau
 </td></tr>,
 <tr>
 <td><a href="/wiki/11th_IIFA_Awards" title="11th IIFA Awards">11th</a></td>
 <td>5 June 2010</td>
 <td><i><a href="/wiki/3_Idiots" title="3 Idiots">3 Idiots</a> </i></td>
 <td><a href="/wiki/Sugathadasa_Stadium" title="Sugathadasa Stadium">Sugathadasa Stadium</a></td>
 <td><a href="/wiki/Colombo" title="Colombo">Colombo</a>, Sri Lanka
 </td></tr>,
 <tr>
 <td><a href="/wiki/12th_IIFA_Awards" title="12th IIFA Awards">12th</a></td>
 <td>25 June 2011</td>
 <td><i><a href="/wiki/Dabangg" title="Dabangg">Dabangg</a> </i></td>
 <td><a href="/wiki/Boman_Irani" title="Boman Irani">Boman Irani</a><br/><a class="mw-redirect" href="/wiki/Ritesh_Deshmukh" title="Ritesh Deshmukh">Ritesh Deshmukh</a></td>
 <td><a href="/wiki/Rogers_Centre" title="Rogers Centre">Rogers Centre</a></td>
 <td><a href="/wiki/Toronto" title="Toronto">Toronto</a>, Canada
 </td></tr>,
 <tr>
 <td><a href="/wiki/13th_IIFA_Awards" title="13th IIFA Awards">13th</a></td>
 <td>9 June 2012</td>
 <td><i><a href="/wiki/Zindagi_Na_Milegi_Dobara" title="Zindagi Na Milegi Dobara">Zindagi Na Milegi Dobara</a> </i></td>
 <td><a href="/wiki/Shahid_Kapoor" title="Shahid Kapoor">Shahid Kapoor</a><br/><a href="/wiki/Farhan_Akhtar" title="Farhan Akhtar">Farhan Akhtar</a></td>
 <td><a href="/wiki/Singapore_Indoor_Stadium" title="Singapore Indoor Stadium">Singapore Indoor Stadium</a></td>
 <td><a href="/wiki/Singapore" title="Singapore">Singapore</a>, Singapore
 </td></tr>,
 <tr>
 <td><a href="/wiki/14th_IIFA_Awards" title="14th IIFA Awards">14th</a></td>
 <td>6 July 2013</td>
 <td><i><a href="/wiki/Barfi!" title="Barfi!">Barfi!</a></i></td>
 <td><a href="/wiki/Salman_Khan" title="Salman Khan">Salman Khan</a><br/><a href="/wiki/Akshay_Kumar" title="Akshay Kumar">Akshay Kumar</a></td>
 <td><a href="/wiki/The_Venetian_Macao" title="The Venetian Macao">The Venetian Macao</a></td>
 <td><a href="/wiki/Macau" title="Macau">Macau</a>, Macau
 </td></tr>,
 <tr>
 <td><a href="/wiki/15th_IIFA_Awards" title="15th IIFA Awards">15th</a></td>
 <td>26 April 2014</td>
 <td><i><a href="/wiki/Bhaag_Milkha_Bhaag" title="Bhaag Milkha Bhaag">Bhaag Milkha Bhaag</a></i></td>
 <td><a href="/wiki/Shahid_Kapoor" title="Shahid Kapoor">Shahid Kapoor</a><br/><a href="/wiki/Farhan_Akhtar" title="Farhan Akhtar">Farhan Akhtar</a></td>
 <td><a href="/wiki/Raymond_James_Stadium" title="Raymond James Stadium">Raymond James Stadium</a></td>
 <td><a class="mw-redirect" href="/wiki/Tampa_Bay_Area" title="Tampa Bay Area">Tampa</a>, United States
 </td></tr>,
 <tr>
 <td><a href="/wiki/16th_IIFA_Awards" title="16th IIFA Awards">16th</a></td>
 <td>7 June 2015</td>
 <td><i><a class="mw-redirect" href="/wiki/Queen_(2014_film)" title="Queen (2014 film)">Queen</a></i></td>
 <td><a href="/wiki/Arjun_Kapoor" title="Arjun Kapoor">Arjun Kapoor</a><br/><a href="/wiki/Ranveer_Singh" title="Ranveer Singh">Ranveer Singh</a></td>
 <td><a class="mw-redirect" href="/wiki/Putra_Indoor_Stadium" title="Putra Indoor Stadium">Putra Indoor Stadium</a></td>
 <td><a href="/wiki/Kuala_Lumpur" title="Kuala Lumpur">Kuala Lumpur</a>, Malaysia
 </td></tr>,
 <tr>
 <td><a href="/wiki/17th_IIFA_Awards" title="17th IIFA Awards">17th</a></td>
 <td>25 June 2016</td>
 <td><i><a href="/wiki/Bajrangi_Bhaijaan" title="Bajrangi Bhaijaan">Bajrangi Bhaijaan</a></i></td>
 <td><a href="/wiki/Shahid_Kapoor" title="Shahid Kapoor">Shahid Kapoor</a><br/><a href="/wiki/Farhan_Akhtar" title="Farhan Akhtar">Farhan Akhtar</a><sup class="reference" id="cite_ref-4"><a href="#cite_note-4"><span class="cite-bracket">[</span>4<span class="cite-bracket">]</span></a></sup></td>
 <td><a class="extiw" href="https://es.wikipedia.org/wiki/Ifema" title="es:Ifema">IFEMA</a></td>
 <td><a href="/wiki/Madrid" title="Madrid">Madrid</a>, Spain
 </td></tr>,
 <tr>
 <td><a href="/wiki/18th_IIFA_Awards" title="18th IIFA Awards">18th</a>
 </td>
 <td>14–15 July 2017<sup class="reference" id="cite_ref-5"><a href="#cite_note-5"><span class="cite-bracket">[</span>5<span class="cite-bracket">]</span></a></sup>
 </td>
 <td><i><a href="/wiki/Neerja" title="Neerja">Neerja</a></i>
 </td>
 <td><a href="/wiki/Karan_Johar" title="Karan Johar">Karan Johar</a>
 <p><a href="/wiki/Saif_Ali_Khan" title="Saif Ali Khan">Saif Ali Khan</a>
 </p>
 </td>
 <td><a href="/wiki/MetLife_Stadium" title="MetLife Stadium">MetLife Stadium</a>
 </td>
 <td><a href="/wiki/East_Rutherford,_New_Jersey" title="East Rutherford, New Jersey">New Jersey</a>, United States
 </td></tr>,
 <tr>
 <td><a href="/wiki/19th_IIFA_Awards" title="19th IIFA Awards">19th</a></td>
 <td>22–24 June 2018</td>
 <td><i><a href="/wiki/Tumhari_Sulu" title="Tumhari Sulu">Tumhari Sulu</a></i></td>
 <td><a href="/wiki/Karan_Johar" title="Karan Johar">Karan Johar</a><br/><a href="/wiki/Riteish_Deshmukh" title="Riteish Deshmukh">Riteish Deshmukh</a></td>
 <td><a href="/wiki/Siam_Niramit" title="Siam Niramit">Siam Niramit Theatre</a></td>
 <td><a href="/wiki/Bangkok" title="Bangkok">Bangkok</a>, Thailand
 </td></tr>,
 <tr>
 <td><a href="/wiki/20th_IIFA_Awards" title="20th IIFA Awards">20th</a></td>
 <td>18 September 2019</td>
 <td><i><a href="/wiki/Raazi" title="Raazi">Raazi</a></i></td>
 <td><a href="/wiki/Ayushmann_Khurrana" title="Ayushmann Khurrana">Ayushmann Khurrana</a><br/><a href="/wiki/Aparshakti_Khurana" title="Aparshakti Khurana">Aparshakti Khurana</a></td>
 <td><a href="/wiki/Sardar_Vallabhbhai_Patel_Indoor_Stadium" title="Sardar Vallabhbhai Patel Indoor Stadium">Sardar Vallabhbhai Patel Indoor Stadium</a></td>
 <td><a href="/wiki/Mumbai" title="Mumbai">Mumbai</a>, India
 </td></tr>,
 <tr>
 <td><a href="/wiki/21st_IIFA_Awards" title="21st IIFA Awards">21st</a></td>
 <td>24 November 2021</td>
 <td><i><a href="/wiki/Kabir_Singh" title="Kabir Singh">Kabir Singh</a></i></td>
 <td colspan="3">The ceremony was cancelled due to <a href="/wiki/COVID-19_pandemic" title="COVID-19 pandemic">COVID-19 pandemic</a>. The winners were announced through <a href="/wiki/Instagram" title="Instagram">Instagram</a>.
 </td></tr>,
 <tr>
 <td><a href="/wiki/22nd_IIFA_Awards" title="22nd IIFA Awards">22nd</a></td>
 <td>2–4 June 2022</td>
 <td><i><a href="/wiki/Shershaah" title="Shershaah">Shershaah</a></i></td>
 <td><a href="/wiki/Salman_Khan" title="Salman Khan">Salman Khan</a> <br/><a href="/wiki/Riteish_Deshmukh" title="Riteish Deshmukh">Riteish Deshmukh</a><br/><a href="/wiki/Maniesh_Paul" title="Maniesh Paul">Maniesh Paul</a></td>
 <td rowspan="3"><a href="/wiki/Etihad_Arena" title="Etihad Arena">Etihad Arena</a></td>
 <td rowspan="3"><a href="/wiki/Abu_Dhabi" title="Abu Dhabi">Abu Dhabi</a>, United Arab Emirates
 </td></tr>,
 <tr>
 <td><a href="/wiki/23rd_IIFA_Awards" title="23rd IIFA Awards">23rd</a></td>
 <td>26–27 May 2023</td>
 <td><i><a href="/wiki/Drishyam_2" title="Drishyam 2">Drishyam 2</a></i></td>
 <td><a href="/wiki/Vicky_Kaushal" title="Vicky Kaushal">Vicky Kaushal</a><br/><a href="/wiki/Abhishek_Bachchan" title="Abhishek Bachchan">Abhishek Bachchan</a>
 </td></tr>,
 <tr>
 <td><a href="/wiki/24th_IIFA_Awards" title="24th IIFA Awards">24th</a>
 </td>
 <td>28 September 2024
 </td>
 <td><i><a href="/wiki/Animal_(2023_Indian_film)" title="Animal (2023 Indian film)">Animal</a></i>
 </td>
 <td><a href="/wiki/Shah_Rukh_Khan" title="Shah Rukh Khan">Shah Rukh Khan</a><br/><a href="/wiki/Karan_Johar" title="Karan Johar">Karan Johar</a><br/><a href="/wiki/Vicky_Kaushal" title="Vicky Kaushal">Vicky Kaushal</a>
 </td></tr>,
 <tr>
 <td><a href="/wiki/25th_IIFA_Awards" title="25th IIFA Awards">25th</a>
 </td>
 <td>8–9 March 2025
 </td>
 <td><i><a href="/wiki/Laapataa_Ladies" title="Laapataa Ladies">Laapataa Ladies</a></i>
 </td>
 <td><a href="/wiki/Karan_Johar" title="Karan Johar">Karan Johar</a>, <a href="/wiki/Kartik_Aaryan" title="Kartik Aaryan">Kartik Aaryan</a>
 </td>
 <td>Jaipur Exhibition &amp; Convention Centre
 </td>
 <td><a href="/wiki/Jaipur" title="Jaipur">Jaipur</a>, India
 </td></tr>]

In [41]:
cer, date, bfilm, hosts, venue, country = [],[],[],[],[],[]
for d in tdata:
    res = d.find_all('td')
    if len(res)==6:
        cer.append(res[0].get_text().strip())
        date.append(res[1].get_text().strip())
        bfilm.append(res[2].get_text().strip())
        host=res[3].get_text().strip()
        ven = res[4].get_text().strip()
        cou = res[5].get_text().strip()
        hosts.append(host)
        venue.append(ven)
        country.append(cou)
    elif len(res) == 5:
        cer.append(res[0].get_text().strip())
        date.append(res[1].get_text().strip())
        bfilm.append(res[2].get_text().strip())
        hosts.append(host)
        venue.append(res[3].get_text().strip())
        country.append(res[4].get_text().strip())
    else:
        cer.append(res[0].get_text().strip())
        date.append(res[1].get_text().strip())
        bfilm.append(res[2].get_text().strip())
        hosts.append(host)
        venue.append(ven)
        country.append(cou)
    
print(len(cer), len(date), len(bfilm), len(hosts), len(venue), len(country))

25 25 25 25 25 25

In [42]:
heads

['Ceremony', 'Date', 'Best Film', 'Host(s)', 'Venue', 'City, Country']

In [44]:
q = [cer, date, bfilm, hosts, venue, country]

In [45]:
list(zip(heads, q))

[('Ceremony',
  ['1st',
   '2nd',
   '3rd',
   '4th',
   '5th',
   '6th',
   '7th',
   '8th',
   '9th',
   '10th',
   '11th',
   '12th',
   '13th',
   '14th',
   '15th',
   '16th',
   '17th',
   '18th',
   '19th',
   '20th',
   '21st',
   '22nd',
   '23rd',
   '24th',
   '25th']),
 ('Date',
  ['24 June 2000',
   '16 June 2001',
   '6 April 2002',
   '17 May 2003',
   '22 May 2004',
   '11 June 2005',
   '17 June 2006',
   '9 June 2007',
   '8 June 2008',
   '13 June 2009',
   '5 June 2010',
   '25 June 2011',
   '9 June 2012',
   '6 July 2013',
   '26 April 2014',
   '7 June 2015',
   '25 June 2016',
   '14–15 July 2017[5]',
   '22–24 June 2018',
   '18 September 2019',
   '24 November 2021',
   '2–4 June 2022',
   '26–27 May 2023',
   '28 September 2024',
   '8–9 March 2025']),
 ('Best Film',
  ['Hum Dil De Chuke Sanam',
   'Kaho Naa... Pyaar Hai',
   'Lagaan',
   'Devdas',
   'Kal Ho Naa Ho',
   'Veer-Zaara',
   'Black',
   'Rang De Basanti',
   'Chak De! India',
   'Jodhaa Akbar',
   '3 Idiots',
   'Dabangg',
   'Zindagi Na Milegi Dobara',
   'Barfi!',
   'Bhaag Milkha Bhaag',
   'Queen',
   'Bajrangi Bhaijaan',
   'Neerja',
   'Tumhari Sulu',
   'Raazi',
   'Kabir Singh',
   'Shershaah',
   'Drishyam 2',
   'Animal',
   'Laapataa Ladies']),
 ('Host(s)',
  ['Yukta Mookhey Anupam Kher',
   'Priyanka ChopraKabir Bedi',
   'Lara Dutta',
   'Anil KapoorDia Mirza',
   'Rahul Khanna',
   'Shahrukh KhanFardeen KhanKaran Johar',
   'Fardeen KhanLara Dutta',
   'Boman IraniLara Dutta',
   'Boman IraniRitesh Deshmukh',
   'Boman IraniRitesh DeshmukhLara Dutta',
   'Boman IraniRitesh DeshmukhLara Dutta',
   'Boman IraniRitesh Deshmukh',
   'Shahid KapoorFarhan Akhtar',
   'Salman KhanAkshay Kumar',
   'Shahid KapoorFarhan Akhtar',
   'Arjun KapoorRanveer Singh',
   'Shahid KapoorFarhan Akhtar[4]',
   'Karan Johar\nSaif Ali Khan',
   'Karan JoharRiteish Deshmukh',
   'Ayushmann KhurranaAparshakti Khurana',
   'Ayushmann KhurranaAparshakti Khurana',
   'Salman Khan Riteish DeshmukhManiesh Paul',
   'Salman Khan Riteish DeshmukhManiesh Paul',
   'Salman Khan Riteish DeshmukhManiesh Paul',
   'Karan Johar, Kartik Aaryan']),
 ('Venue',
  ['Millennium Dome',
   'Superbowl Arena',
   'Arena of Stars',
   'Coca-Cola Dome',
   'Singapore Indoor Stadium',
   'Amsterdam Arena',
   'Dubai International Convention Centre',
   'Hallam FM Arena',
   'Siam Paragon',
   'The Venetian Macao',
   'Sugathadasa Stadium',
   'Rogers Centre',
   'Singapore Indoor Stadium',
   'The Venetian Macao',
   'Raymond James Stadium',
   'Putra Indoor Stadium',
   'IFEMA',
   'MetLife Stadium',
   'Siam Niramit Theatre',
   'Sardar Vallabhbhai Patel Indoor Stadium',
   'Sardar Vallabhbhai Patel Indoor Stadium',
   'Etihad Arena',
   'Etihad Arena',
   'Etihad Arena',
   'Jaipur Exhibition & Convention Centre']),
 ('City, Country',
  ['London, United Kingdom',
   'Sun City, South Africa',
   'Genting Highlands, Malaysia',
   'Johannesburg, South Africa',
   'Singapore, Singapore',
   'Amsterdam, Netherlands',
   'Dubai, United Arab Emirates',
   'Sheffield, United Kingdom',
   'Bangkok, Thailand',
   'Macau, Macau',
   'Colombo, Sri Lanka',
   'Toronto, Canada',
   'Singapore, Singapore',
   'Macau, Macau',
   'Tampa, United States',
   'Kuala Lumpur, Malaysia',
   'Madrid, Spain',
   'New Jersey, United States',
   'Bangkok, Thailand',
   'Mumbai, India',
   'Mumbai, India',
   'Abu Dhabi, United Arab Emirates',
   'Abu Dhabi, United Arab Emirates',
   'Abu Dhabi, United Arab Emirates',
   'Jaipur, India'])]

In [46]:
d = dict(list(zip(heads, q)))
d

{'Ceremony': ['1st',
  '2nd',
  '3rd',
  '4th',
  '5th',
  '6th',
  '7th',
  '8th',
  '9th',
  '10th',
  '11th',
  '12th',
  '13th',
  '14th',
  '15th',
  '16th',
  '17th',
  '18th',
  '19th',
  '20th',
  '21st',
  '22nd',
  '23rd',
  '24th',
  '25th'],
 'Date': ['24 June 2000',
  '16 June 2001',
  '6 April 2002',
  '17 May 2003',
  '22 May 2004',
  '11 June 2005',
  '17 June 2006',
  '9 June 2007',
  '8 June 2008',
  '13 June 2009',
  '5 June 2010',
  '25 June 2011',
  '9 June 2012',
  '6 July 2013',
  '26 April 2014',
  '7 June 2015',
  '25 June 2016',
  '14–15 July 2017[5]',
  '22–24 June 2018',
  '18 September 2019',
  '24 November 2021',
  '2–4 June 2022',
  '26–27 May 2023',
  '28 September 2024',
  '8–9 March 2025'],
 'Best Film': ['Hum Dil De Chuke Sanam',
  'Kaho Naa... Pyaar Hai',
  'Lagaan',
  'Devdas',
  'Kal Ho Naa Ho',
  'Veer-Zaara',
  'Black',
  'Rang De Basanti',
  'Chak De! India',
  'Jodhaa Akbar',
  '3 Idiots',
  'Dabangg',
  'Zindagi Na Milegi Dobara',
  'Barfi!',
  'Bhaag Milkha Bhaag',
  'Queen',
  'Bajrangi Bhaijaan',
  'Neerja',
  'Tumhari Sulu',
  'Raazi',
  'Kabir Singh',
  'Shershaah',
  'Drishyam 2',
  'Animal',
  'Laapataa Ladies'],
 'Host(s)': ['Yukta Mookhey Anupam Kher',
  'Priyanka ChopraKabir Bedi',
  'Lara Dutta',
  'Anil KapoorDia Mirza',
  'Rahul Khanna',
  'Shahrukh KhanFardeen KhanKaran Johar',
  'Fardeen KhanLara Dutta',
  'Boman IraniLara Dutta',
  'Boman IraniRitesh Deshmukh',
  'Boman IraniRitesh DeshmukhLara Dutta',
  'Boman IraniRitesh DeshmukhLara Dutta',
  'Boman IraniRitesh Deshmukh',
  'Shahid KapoorFarhan Akhtar',
  'Salman KhanAkshay Kumar',
  'Shahid KapoorFarhan Akhtar',
  'Arjun KapoorRanveer Singh',
  'Shahid KapoorFarhan Akhtar[4]',
  'Karan Johar\nSaif Ali Khan',
  'Karan JoharRiteish Deshmukh',
  'Ayushmann KhurranaAparshakti Khurana',
  'Ayushmann KhurranaAparshakti Khurana',
  'Salman Khan Riteish DeshmukhManiesh Paul',
  'Salman Khan Riteish DeshmukhManiesh Paul',
  'Salman Khan Riteish DeshmukhManiesh Paul',
  'Karan Johar, Kartik Aaryan'],
 'Venue': ['Millennium Dome',
  'Superbowl Arena',
  'Arena of Stars',
  'Coca-Cola Dome',
  'Singapore Indoor Stadium',
  'Amsterdam Arena',
  'Dubai International Convention Centre',
  'Hallam FM Arena',
  'Siam Paragon',
  'The Venetian Macao',
  'Sugathadasa Stadium',
  'Rogers Centre',
  'Singapore Indoor Stadium',
  'The Venetian Macao',
  'Raymond James Stadium',
  'Putra Indoor Stadium',
  'IFEMA',
  'MetLife Stadium',
  'Siam Niramit Theatre',
  'Sardar Vallabhbhai Patel Indoor Stadium',
  'Sardar Vallabhbhai Patel Indoor Stadium',
  'Etihad Arena',
  'Etihad Arena',
  'Etihad Arena',
  'Jaipur Exhibition & Convention Centre'],
 'City, Country': ['London, United Kingdom',
  'Sun City, South Africa',
  'Genting Highlands, Malaysia',
  'Johannesburg, South Africa',
  'Singapore, Singapore',
  'Amsterdam, Netherlands',
  'Dubai, United Arab Emirates',
  'Sheffield, United Kingdom',
  'Bangkok, Thailand',
  'Macau, Macau',
  'Colombo, Sri Lanka',
  'Toronto, Canada',
  'Singapore, Singapore',
  'Macau, Macau',
  'Tampa, United States',
  'Kuala Lumpur, Malaysia',
  'Madrid, Spain',
  'New Jersey, United States',
  'Bangkok, Thailand',
  'Mumbai, India',
  'Mumbai, India',
  'Abu Dhabi, United Arab Emirates',
  'Abu Dhabi, United Arab Emirates',
  'Abu Dhabi, United Arab Emirates',
  'Jaipur, India']}

In [47]:
df = pd.DataFrame(d)
df

,Ceremony,Date,Best Film,Host(s),Venue,"City, Country"
0,1st,24 June 2000,Hum Dil De Chuke Sanam,Yukta Mookhey Anupam Kher,Millennium Dome,"London, United Kingdom"
1,2nd,16 June 2001,Kaho Naa... Pyaar Hai,Priyanka ChopraKabir Bedi,Superbowl Arena,"Sun City, South Africa"
2,3rd,6 April 2002,Lagaan,Lara Dutta,Arena of Stars,"Genting Highlands, Malaysia"
3,4th,17 May 2003,Devdas,Anil KapoorDia Mirza,Coca-Cola Dome,"Johannesburg, South Africa"
4,5th,22 May 2004,Kal Ho Naa Ho,Rahul Khanna,Singapore Indoor Stadium,"Singapore, Singapore"
5,6th,11 June 2005,Veer-Zaara,Shahrukh KhanFardeen KhanKaran Johar,Amsterdam Arena,"Amsterdam, Netherlands"
6,7th,17 June 2006,Black,Fardeen KhanLara Dutta,Dubai International Convention Centre,"Dubai, United Arab Emirates"
7,8th,9 June 2007,Rang De Basanti,Boman IraniLara Dutta,Hallam FM Arena,"Sheffield, United Kingdom"
8,9th,8 June 2008,Chak De! India,Boman IraniRitesh Deshmukh,Siam Paragon,"Bangkok, Thailand"
9,10th,13 June 2009,Jodhaa Akbar,Boman IraniRitesh DeshmukhLara Dutta,The Venetian Macao,"Macau, Macau"
10,11th,5 June 2010,3 Idiots,Boman IraniRitesh DeshmukhLara Dutta,Sugathadasa Stadium,"Colombo, Sri Lanka"
11,12th,25 June 2011,Dabangg,Boman IraniRitesh Deshmukh,Rogers Centre,"Toronto, Canada"
12,13th,9 June 2012,Zindagi Na Milegi Dobara,Shahid KapoorFarhan Akhtar,Singapore Indoor Stadium,"Singapore, Singapore"
13,14th,6 July 2013,Barfi!,Salman KhanAkshay Kumar,The Venetian Macao,"Macau, Macau"
14,15th,26 April 2014,Bhaag Milkha Bhaag,Shahid KapoorFarhan Akhtar,Raymond James Stadium,"Tampa, United States"
15,16th,7 June 2015,Queen,Arjun KapoorRanveer Singh,Putra Indoor Stadium,"Kuala Lumpur, Malaysia"
16,17th,25 June 2016,Bajrangi Bhaijaan,Shahid KapoorFarhan Akhtar[4],IFEMA,"Madrid, Spain"
17,18th,14–15 July 2017[5],Neerja,Karan Johar\nSaif Ali Khan,MetLife Stadium,"New Jersey, United States"
18,19th,22–24 June 2018,Tumhari Sulu,Karan JoharRiteish Deshmukh,Siam Niramit Theatre,"Bangkok, Thailand"
19,20th,18 September 2019,Raazi,Ayushmann KhurranaAparshakti Khurana,Sardar Vallabhbhai Patel Indoor Stadium,"Mumbai, India"
20,21st,24 November 2021,Kabir Singh,Ayushmann KhurranaAparshakti Khurana,Sardar Vallabhbhai Patel Indoor Stadium,"Mumbai, India"
21,22nd,2–4 June 2022,Shershaah,Salman Khan Riteish DeshmukhManiesh Paul,Etihad Arena,"Abu Dhabi, United Arab Emirates"
22,23rd,26–27 May 2023,Drishyam 2,Salman Khan Riteish DeshmukhManiesh Paul,Etihad Arena,"Abu Dhabi, United Arab Emirates"
23,24th,28 September 2024,Animal,Salman Khan Riteish DeshmukhManiesh Paul,Etihad Arena,"Abu Dhabi, United Arab Emirates"
24,25th,8–9 March 2025,Laapataa Ladies,"Karan Johar, Kartik Aaryan",Jaipur Exhibition & Convention Centre,"Jaipur, India"

In [48]:
for i in range(1, 11):
    url = f"https://www.ambitionbox.com/list-of-companies?page={i}"
    print(url)

https://www.ambitionbox.com/list-of-companies?page=1
https://www.ambitionbox.com/list-of-companies?page=2
https://www.ambitionbox.com/list-of-companies?page=3
https://www.ambitionbox.com/list-of-companies?page=4
https://www.ambitionbox.com/list-of-companies?page=5
https://www.ambitionbox.com/list-of-companies?page=6
https://www.ambitionbox.com/list-of-companies?page=7
https://www.ambitionbox.com/list-of-companies?page=8
https://www.ambitionbox.com/list-of-companies?page=9
https://www.ambitionbox.com/list-of-companies?page=10